// ============ DAILY KNOWLEDGE BANKS ============
// Each pool rotates daily. To add entries, APPEND to the end of a pool.
const DAILY = {

vocab: [
 {w:"Candid", d:"Honest and direct, even when it's a little uncomfortable.", x:"Be candid with me — does this plan have problems?"},
 {w:"Pragmatic", d:"Focused on what actually works, not what sounds ideal.", x:"She took the pragmatic route and fixed the leak before repainting."},
 {w:"Resilient", d:"Able to bounce back quickly from setbacks.", x:"The team stayed resilient after losing the first contract."},
 {w:"Eloquent", d:"Speaking or writing in a clear, powerful, persuasive way.", x:"His eloquent toast had the whole room in tears."},
 {w:"Meticulous", d:"Extremely careful about every small detail.", x:"She kept meticulous records of every expense."},
 {w:"Ambivalent", d:"Having mixed feelings — pulled in two directions at once.", x:"I'm ambivalent about moving: excited, but I'd miss everyone."},
 {w:"Tenacious", d:"Holding on and refusing to give up.", x:"He was tenacious about learning guitar, practicing every night."},
 {w:"Prudent", d:"Showing careful, sensible judgment about the future.", x:"It's prudent to save before you splurge."},
 {w:"Gregarious", d:"Sociable — someone who genuinely enjoys being around people.", x:"Our gregarious neighbor knows everyone on the street."},
 {w:"Succinct", d:"Said completely, in very few words.", x:"Keep the email succinct: three sentences, one ask."},
 {w:"Empathy", d:"Feeling with someone — understanding their feelings from the inside.", x:"She listened with real empathy instead of jumping to advice."},
 {w:"Frugal", d:"Careful and smart with money — not cheap, just intentional.", x:"He's frugal with gadgets but generous with gifts."},
 {w:"Diligent", d:"Working with steady, careful, reliable effort.", x:"A diligent student beats a brilliant lazy one most days."},
 {w:"Skeptical", d:"Questioning claims before believing them.", x:"Be skeptical of any deal that demands a decision today."},
 {w:"Adaptable", d:"Able to adjust smoothly when things change.", x:"Plans collapsed, but she's adaptable — they ate picnic-style in the car."},
 {w:"Articulate", d:"Able to put thoughts into clear words.", x:"Practice helped him become articulate in meetings."},
 {w:"Benevolent", d:"Kind-hearted; wanting good things for others.", x:"A benevolent stranger paid for their coffee."},
 {w:"Candor", d:"Refreshing, open honesty.", x:"I appreciated her candor about the job's downsides."},
 {w:"Concise", d:"Short, but missing nothing important.", x:"A concise resume gets read; a long one gets skimmed."},
 {w:"Credible", d:"Believable and trustworthy.", x:"Check if the source is credible before sharing the story."},
 {w:"Discreet", d:"Careful with sensitive information; not drawing attention.", x:"Be discreet — they haven't announced the news yet."},
 {w:"Earnest", d:"Deeply sincere and serious about something.", x:"His earnest apology repaired the friendship."},
 {w:"Feasible", d:"Actually possible to do.", x:"Is it feasible to finish by Friday, honestly?"},
 {w:"Genuine", d:"Real, authentic, exactly what it appears to be.", x:"Her interest in your story was genuine — she remembered every detail."},
 {w:"Humble", d:"Modest about your own achievements.", x:"He stayed humble even after the promotion."},
 {w:"Impartial", d:"Fair to all sides; playing no favorites.", x:"A good referee stays impartial."},
 {w:"Integrity", d:"Doing the right thing even when nobody is watching.", x:"Returning the extra change was a small act of integrity."},
 {w:"Jovial", d:"Cheerful, warm, and good-humored.", x:"Their jovial uncle turns every dinner into a party."},
 {w:"Lucid", d:"Crystal clear and easy to understand.", x:"She gave a lucid explanation of a confusing tax form."},
 {w:"Mediate", d:"To help two sides find an agreement.", x:"Mom had to mediate the great bedroom-sharing dispute."},
 {w:"Nuance", d:"A subtle difference that changes the meaning.", x:"There's a nuance between 'I'm fine' and 'I'm fine.'"},
 {w:"Objective", d:"Based on facts, not personal feelings.", x:"Try to stay objective when judging your own work."},
 {w:"Persevere", d:"To keep going even when it's hard.", x:"She persevered through three rejections before the yes."},
 {w:"Rapport", d:"A relationship of easy mutual understanding and trust.", x:"He builds rapport by remembering people's kids' names."},
 {w:"Savvy", d:"Practical, street-smart know-how.", x:"Ask your tech-savvy cousin before buying the laptop."},
 {w:"Tactful", d:"Honest in a way that doesn't wound.", x:"A tactful way to decline: 'I'm honored, but I can't commit to it properly.'"},
 {w:"Ubiquitous", d:"Seemingly everywhere at once.", x:"QR-code menus became ubiquitous almost overnight."},
 {w:"Validate", d:"To confirm something — or someone's feelings — as real and reasonable.", x:"Validate first ('that IS frustrating'), solve second."},
 {w:"Wary", d:"Alert and cautious about possible danger.", x:"Be wary of links in unexpected text messages."},
 {w:"Zealous", d:"Intensely, actively enthusiastic.", x:"He's zealous about composting — the whole block recycles now."},
 {w:"Advocate", d:"To speak up in support of someone or something.", x:"Learn to advocate for yourself at the doctor's office."},
 {w:"Brevity", d:"The art of pleasing shortness.", x:"Brevity is a gift in meetings — say it, then stop."},
 {w:"Catalyst", d:"The thing that sparks a change.", x:"One honest conversation was the catalyst for the whole turnaround."},
 {w:"Deliberate", d:"Done slowly, carefully, and on purpose.", x:"Make big purchases deliberate, not impulsive."},
 {w:"Equitable", d:"Fair — everyone gets what they actually need.", x:"They found an equitable way to split the chores."},
 {w:"Foresight", d:"The ability to see what's coming and prepare.", x:"Buying snow tires in September was pure foresight."},
 {w:"Hindsight", d:"Understanding something only after it happens.", x:"In hindsight, the cheap flight with two layovers wasn't cheap."},
 {w:"Initiative", d:"Acting without waiting to be told.", x:"She showed initiative and fixed the process nobody owned."},
 {w:"Jargon", d:"Insider language that outsiders can't follow.", x:"Skip the jargon — explain it like I'm not in your industry."},
 {w:"Leverage", d:"Using something you have to get the most advantage.", x:"Use your job offer as leverage in the salary talk."},
 {w:"Momentum", d:"Progress that builds on itself and gets easier.", x:"Don't break the streak — momentum is doing half the work."},
 {w:"Negotiate", d:"To reach a deal through discussion.", x:"Almost everything is negotiable if you ask politely."},
 {w:"Pivotal", d:"So important that everything turns on it.", x:"The pivotal moment was asking for help."},
 {w:"Quintessential", d:"The most perfect example of something.", x:"A lemonade stand is the quintessential first business."},
 {w:"Rational", d:"Based on reason and logic.", x:"Sleep on it — make the rational choice in the morning."},
 {w:"Scrutinize", d:"To examine extremely closely.", x:"Scrutinize any contract before you sign it."},
 {w:"Transparent", d:"Completely open, with nothing hidden.", x:"Good landlords are transparent about fees up front."},
 {w:"Unanimous", d:"Agreed by absolutely everyone.", x:"The vote for pizza was unanimous."},
 {w:"Versatile", d:"Useful or skilled in many different ways.", x:"A cast-iron pan is the most versatile thing in the kitchen."},
 {w:"Altruism", d:"Helping others with no expectation of reward.", x:"Anonymous donations are altruism in its purest form."},
 {w:"Composure", d:"Staying calm and steady under pressure.", x:"She kept her composure through the whole emergency."},
 {w:"Decorum", d:"Behavior that fits the occasion.", x:"Funerals, weddings, interviews — each has its own decorum."},
 {w:"Mitigate", d:"To make something less severe.", x:"Sunscreen mitigates the damage; shade prevents it."},
 {w:"Consensus", d:"A general agreement the whole group can live with.", x:"We reached consensus: tacos Tuesday, forever."},
 {w:"Anomaly", d:"Something that doesn't fit the normal pattern.", x:"One weird charge on the statement is an anomaly worth a phone call."},
 {w:"Fortitude", d:"Courage that endures through pain or hardship.", x:"It took fortitude to start over in a new city at 50."},
 {w:"Cohesive", d:"Sticking together as one connected whole.", x:"A cohesive team disagrees in the room and defends each other outside it."},
 {w:"Procrastinate", d:"To delay the thing you know you should do.", x:"If you tend to procrastinate, shrink the task to two minutes."},
 {w:"Optimal", d:"The best possible under the circumstances.", x:"The optimal nap is about 20 minutes."},
 {w:"Serendipity", d:"A happy accident — finding good things you weren't looking for.", x:"Meeting her at the wrong bus stop was pure serendipity."}
],

body: [
 {f:"Your heart beats about 100,000 times a day — without a single day off.", a:"Give it backup: a brisk 20-minute walk today counts as real cardio."},
 {f:"You're roughly 60% water. Even mild dehydration shows up as fatigue and headaches first.", a:"Check your urine color: pale yellow = good, apple juice = drink up."},
 {f:"Skin is your largest organ, and most aging is sun damage, not time.", a:"Sunscreen on your face every morning — cloudy days too."},
 {f:"You sleep in roughly 90-minute cycles. Waking mid-cycle is why you feel groggy.", a:"Set your alarm in multiples of 90 minutes from when you fall asleep (e.g., 7.5 hours)."},
 {f:"Caffeine has a half-life of 5–6 hours. A 4pm coffee is still half-active at 10pm.", a:"Make 2pm your caffeine cutoff for one week and watch your sleep improve."},
 {f:"Starting in your 30s, you lose 3–8% of muscle per decade — unless you fight back.", a:"Lift something heavy twice a week. Bodyweight squats count."},
 {f:"Your skeleton fully rebuilds itself about every 10 years.", a:"Bones grow stronger under load: walking, stairs, weights — give them a reason."},
 {f:"Your gut hosts trillions of bacteria that affect mood, immunity, and weight.", a:"Feed the good ones: add one fiber-rich food today (beans, oats, apples)."},
 {f:"Screens make you blink 60% less, which is why your eyes burn by evening.", a:"The 20-20-20 rule: every 20 minutes, look 20 feet away for 20 seconds."},
 {f:"Hearing damage starts around 85 decibels — about the level of loud headphones.", a:"Keep volume under 60% — hearing doesn't grow back."},
 {f:"Your brain is 2% of your body weight but burns about 20% of your energy.", a:"Brain fog is often just fuel shortage: water, food, or sleep — check all three."},
 {f:"Sitting for hours stiffens more than your back — it slows your whole metabolism.", a:"Stand or walk for 2–3 minutes every half hour. Set a timer once today."},
 {f:"Grip strength is one of the best predictors of healthy aging ever measured.", a:"Carry the groceries in one trip. Hang from a bar. Use your hands hard."},
 {f:"Tooth enamel never grows back — it's the one part of you that can't heal.", a:"Soft brush, gentle circles, and wait 30 minutes to brush after acidic drinks."},
 {f:"Flossing cleans the 40% of tooth surface your brush physically cannot reach.", a:"Floss tonight. Just tonight. (That's how streaks start.)"},
 {f:"Your liver performs over 500 different jobs — and it's the only organ that regrows.", a:"Give it scheduled days off: pick two alcohol-free days every week."},
 {f:"Your kidneys filter your entire blood supply about 60 times a day.", a:"They run on water. A glass first thing in the morning is the easiest favor you can do them."},
 {f:"Unfolded, your lungs' surface would cover a tennis court.", a:"Use the capacity: three slow, deep breaths right now. Notice the difference."},
 {f:"A fever is your immune system turning up the heat on purpose to fight invaders.", a:"Treat the discomfort, not just the number — and call a doctor for very high or long fevers."},
 {f:"Goosebumps are a leftover reflex from when your ancestors had fur to fluff up.", a:"Your body carries millions of years of history. Be a little amazed today."},
 {f:"Cracking your knuckles is just gas bubbles popping — studies show it doesn't cause arthritis.", a:"Tell the person who's been scolding you. You're welcome."},
 {f:"Your stomach lining replaces itself every few days — otherwise your own acid would digest it.", a:"Help it out: slow down when you eat. Chewing is the first half of digestion."},
 {f:"You're about a centimeter taller in the morning — your spine discs compress during the day.", a:"Morning stretches work with your body's schedule. Try a slow reach-for-the-sky."},
 {f:"A drop of blood does a complete loop of your entire body in about 60 seconds.", a:"Raise your heart rate for 10 minutes today — every cell gets the delivery faster."},
 {f:"Your body makes vitamin D from sunlight — and most people run low in winter.", a:"Get 10–20 minutes of daylight today, or ask your doctor about a supplement."},
 {f:"Melatonin — your sleep hormone — rises with darkness and is crushed by bright screens.", a:"Dim screens (or use night mode) for the last hour before bed."},
 {f:"The perfect nap is about 20 minutes — longer drops you into deep sleep and you wake up worse.", a:"If you nap today, set a 20-minute alarm. Wake up sharp instead of groggy."},
 {f:"Thirst lags behind dehydration — by the time you feel it, you're already low.", a:"In heat or exercise, drink on a schedule, not on thirst."},
 {f:"About 70% of the salt you eat comes from packaged food — not your salt shaker.", a:"Flip one package today and read the sodium line. It's educational."},
 {f:"One can of soda blows past the recommended daily added-sugar limit by itself.", a:"Swap one sugary drink for water or sparkling water today."},
 {f:"Most people eat half the fiber they need — and fiber feeds your gut, heart, and blood sugar.", a:"Easy +5 grams: a bowl of oats, an apple with skin, or a handful of beans."},
 {f:"Your body absorbs protein better spread across the day than in one giant dinner.", a:"Add some protein to breakfast — eggs, yogurt, or peanut butter."},
 {f:"Your liver processes about one drink per hour. Coffee, showers, and food don't speed it up.", a:"Plan rides BEFORE celebrations, not during."},
 {f:"Cortisol (your wake-up hormone) peaks naturally in the first hour after waking.", a:"Try coffee 60–90 minutes after waking — it hits harder when cortisol dips."},
 {f:"A 10-minute walk after eating noticeably flattens your blood sugar spike.", a:"After your biggest meal today, walk around the block."},
 {f:"Cold muscles don't like stretching — warm them first, stretch after.", a:"Before exercise: easy movement. After: that's stretch time."},
 {f:"Balance fades silently for decades — then announces itself with a fall.", a:"Stand on one foot while brushing your teeth. 30 seconds per side."},
 {f:"VO2 max — how much oxygen you can use — is a top predictor of long life.", a:"Once this week, push hard enough that talking gets difficult, for 1 minute, 4 times."},
 {f:"Your head weighs about 10–12 pounds — bent over a phone, your neck feels up to 5x that.", a:"Raise the phone to eye level. Your future neck says thanks."},
 {f:"Long, slow exhales activate the nerve that calms your whole body (the vagus nerve).", a:"Try it: in for 4, out for 8, five times. That's a built-in chill switch."},
 {f:"A sneeze leaves your body at up to 100 mph.", a:"Aim it at your elbow, not your hand — hands touch everything."},
 {f:"Washing hands for 20 seconds is one of the most powerful health technologies ever found.", a:"Today, actually count to 20. Most people stop at 6."},
 {f:"Antibiotics kill bacteria but do absolutely nothing against viruses like colds and flu.", a:"Never pressure a doctor for antibiotics — and take prescribed ones exactly as directed."},
 {f:"Vaccines are a 'wanted poster' for your immune system — training without the disease.", a:"Check if you're due for any boosters. Adults forget tetanus (every 10 years)."},
 {f:"Skin cancer is the most common cancer — and one of the most curable when caught early.", a:"Learn ABCDE for moles: Asymmetry, Border, Color, Diameter, Evolving. Check your skin this week."},
 {f:"High blood pressure has zero symptoms — that's why it's called the silent killer.", a:"Know your numbers. Many pharmacies check it free."},
 {f:"Your resting heart rate is a free fitness tracker — lower over time usually means fitter.", a:"Check your pulse before getting out of bed tomorrow. Write it down."},
 {f:"Ears clean themselves — cotton swabs mostly pack wax deeper.", a:"Swab the outside only. Your eardrum is not a target."},
 {f:"Fingernails grow about 3mm a month, and changes in them can signal health issues.", a:"Ridges, color changes, or spooning are worth mentioning at your next checkup."},
 {f:"Sweat itself is odorless — it's skin bacteria having lunch that makes the smell.", a:"That's why deodorant targets bacteria, and why fabrics matter. Wash gym clothes promptly."},
 {f:"Hiccups are your diaphragm spasming — the breathing muscle under your lungs.", a:"Best evidence trick: breathe in fully, hold 10 seconds, exhale slow. Repeat 3 times."},
 {f:"A huge share of bad breath comes from the tongue, not the teeth.", a:"Brush or scrape your tongue tonight. (Gently. You'll know if it's working.)"},
 {f:"Your brain itself can't feel pain — headaches come from vessels, muscles, and nerves around it.", a:"Most common headache triggers: dehydration, screens, posture, and skipped meals. Audit yours."},
 {f:"Your brain files memories during sleep — study without sleep is like typing without saving.", a:"Learning something? Review it once before bed tonight."},
 {f:"Genuine laughter lowers stress hormones and gives your immune system a measurable nudge.", a:"Prescription: one thing that actually makes you laugh, today. Doctor's orders from 2150."},
 {f:"After about age 40, your eyes' lenses stiffen — that's why menus drift to arm's length.", a:"It's normal (presbyopia). Reading glasses from the pharmacy are fine to start; get a real eye exam every 1–2 years."},
 {f:"Untreated hearing loss is one of the biggest modifiable risk factors for dementia.", a:"If people 'mumble' lately, book a hearing test. Hearing aids protect the brain, not just the ears."},
 {f:"Strength training also strengthens bone — it can slow or partially reverse bone thinning.", a:"Squats, stairs, and carrying things: your skeleton's favorite gifts."},
 {f:"Your appendix isn't useless — it likely serves as a 'safe house' for good gut bacteria.", a:"Know appendicitis signs anyway: pain that moves to the lower right belly + fever = ER."},
 {f:"Blushing, racing heart, sweaty palms — anxiety and excitement are nearly identical in the body.", a:"Try relabeling: say 'I'm excited' before stressful moments. Studies show it actually helps performance."}
],

money: [
 // ── Universal (all ages) ──────────────────────────────────────────────────
 {h:"Compound interest is the whole game", d:"Money earns money, then THAT money earns money. $100/month from age 25 beats $300/month from age 45. Starting early matters more than starting big."},
 {h:"Pay yourself first", d:"Savings that wait for 'whatever's left over' get nothing. Automate a transfer on payday — even $20 — and you'll never miss it."},
 {h:"The $1,000 force field", d:"A starter emergency fund turns a 'dead phone' moment from a credit-card spiral into an inconvenience. Build this before almost anything else."},
 {h:"Read the unit price", d:"The tiny number on the shelf tag (price per ounce/count) is the only honest number in the store. Big packages aren't always cheaper."},
 {h:"Audit your subscriptions twice a year", d:"Streaming, apps, boxes, memberships — companies bet on your forgetfulness. Tonight: scroll your last statement and cancel one thing."},
 {h:"The Rule of 72", d:"Divide 72 by your interest rate to see how long money takes to double. At 8%, money doubles every 9 years. (It works for debt too — scary.)"},
 {h:"The 24-hour rule", d:"See it, want it, wait one day. If you still want it tomorrow, fine. Most wants don't survive the night — that's not weakness, that's marketing wearing off."},
 {h:"Anchoring is a trick", d:"'Was $200, now $89!' — the $200 exists only to make $89 feel like winning. Judge every price as if you'd never seen the 'original.'"},
 {h:"Urgency is the universal scam tell", d:"'Act NOW.' 'Your account closes TODAY.' Real institutions don't rush you. The faster someone pushes, the slower you should move."},
 {h:"Buy-now-pay-later is still debt", d:"Four easy payments of $25 is a $100 you may not have. BNPL trains your brain to ignore totals. Add up everything you owe across those apps — today."},
 {h:"Try the store brand once", d:"Generics are often made in the same factories as name brands — medicine especially (same active ingredient, by law). Try one swap this week."},
 {h:"Never shop hungry, never shop without a list", d:"Stores are engineered to ambush you — eye-level placement, smells, endcaps. A list and a full stomach are body armor."},
 {h:"The 5-minute weekly money check", d:"Once a week, glance at every account: anything weird, anything forgotten, anything due? Five minutes of attention prevents 90% of money surprises."},
 {h:"Tipping in the US: the cheat sheet", d:"Sit-down service: 18–20%. Delivery: 15–20% or a few dollars minimum. Counter tip jars: optional. When someone carries, fixes, or rescues — cash says thanks best."},
 {h:"Buy experiences, mostly", d:"Studies keep finding it: the joy of stuff fades fast; experiences appreciate in memory. The concert outlasts the gadget."},
 // ── Teen-only (under 18) ──────────────────────────────────────────────────
 {h:"Needs vs. wants — the core skill", d:"Food, a ride to school, a winter coat: need. New sneakers, the game that just dropped, extra snacks: want. This one distinction, made on purpose every time, is more powerful than any budget app.", teen:1},
 {h:"Save before you spend", d:"The moment money lands — allowance, birthday gift, paycheck — put 20% somewhere it's not easy to reach. Not after you buy things. Before. Everything else is leftovers math.", teen:1},
 {h:"Your first paycheck will surprise you", d:"The number on your offer isn't what hits your account. Taxes and other deductions come out first. Budget from what actually deposits, not hourly rate times hours.", teen:1},
 {h:"A goal with a number and a date actually works", d:"'Save more money' fails every time. '$300 by August for that concert' works. Pick the thing, write the number, count the weeks, divide. Now you have a plan — not a wish.", teen:1},
 {h:"Time is your biggest money advantage", d:"You have something most adults wish they could buy back: time. $500 saved at 14, left alone growing at 8%, becomes ~$17,000 by the time you're 60. You don't need much — you need early.", teen:1},
 {h:"Never lend what you'd be hurt to lose", d:"If a friend asks for $20, only hand it over if you'd be fine never seeing it back. Real friendship isn't worth a loan. Think of it as a gift in your head and decide from there.", teen:1},
 {h:"Small income is real income", d:"Babysitting, mowing lawns, selling stuff online, a few hours at a local place — $50 a week is $2,600 a year. That's a laptop, a trip, or the start of a real savings account. Small adds up fast.", teen:1},
 {h:"The social spend trap is real", d:"'Everyone's going, just come' is often code for 'spend $40 you didn't plan for.' It's okay to say 'I'll catch the next one' or 'I'm saving right now.' Your real friends won't care.", teen:1},
 // ── Adult-only (18+) ─────────────────────────────────────────────────────
 {h:"The 50/30/20 starting map", d:"Roughly: 50% needs, 30% wants, 20% saving and debt payoff. Don't worship it — use it to find out where you actually stand.", a18:1},
 {h:"Credit utilization: stay under 30%", d:"Using too much of your credit limit drags your score down — even if you pay in full. Under 30% is good; under 10% is excellent.", a18:1},
 {h:"Beware lifestyle creep", d:"Every raise quietly becomes a nicer car and fancier groceries. Next raise: bump your savings rate FIRST, then enjoy the rest guilt-free.", a18:1},
 {h:"Deductibles are a dial", d:"Higher deductible = lower monthly premium. Set it to the biggest amount you could actually pay tomorrow — then pocket the savings.", a18:1},
 {h:"Loyalty is taxed", d:"Internet, insurance, and phone companies save the best prices for new customers. Call once a year: 'I'm considering switching — what can you do?'", a18:1},
 {h:"The 3-year-old car trick", d:"New cars lose ~30% of their value in 3 years. Buying a 3-year-old car with low miles means someone else paid that bill for you.", a18:1},
 {h:"Index funds beat the pros", d:"Decade after decade, low-cost index funds outperform most professional stock pickers. Boring wins. That's the secret nobody profits from telling you.", a18:1},
 {h:"Dollar-cost averaging", d:"Invest the same amount on the same day every month, ignoring the news. You automatically buy more when it's cheap. Discipline disguised as laziness.", a18:1},
 {h:"The 401(k) match is free money", d:"If your employer matches contributions, that's an instant 100% return — the best deal you will ever be offered. Take all of it.", a18:1},
 {h:"What your credit score is made of", d:"Payment history (35%) and how much credit you're using (30%) are most of it. Translation: pay on time, every time, and keep balances low.", a18:1},
 {h:"Avalanche vs. snowball", d:"Avalanche = pay highest interest rate first (best math). Snowball = pay smallest balance first (best motivation). The best method is whichever one you'll stick to.", a18:1},
 {h:"Sales run on a calendar", d:"TVs around the big game, mattresses on holiday weekends, cars at month-end (quotas are real). Time big purchases instead of buying on impulse.", a18:1},
 {h:"Skip most extended warranties", d:"They're priced so the store almost always wins. Self-insure small stuff with your emergency fund; many credit cards extend warranties free anyway.", a18:1},
 {h:"Track one number: net worth", d:"Everything you own minus everything you owe. Check it quarterly. The trend matters more than the number — is the line going up?", a18:1},
 {h:"Renters insurance is absurdly cheap", d:"Around $15/month covers everything you own against fire, theft, and water — plus liability. The landlord's policy covers the building, not your stuff.", a18:1},
 {h:"Beneficiary forms beat wills", d:"Whoever's named on your 401(k), IRA, and life insurance gets the money — even if your will says otherwise. Check yours after every big life change.", a18:1},
 {h:"Freeze your credit — it's free", d:"A credit freeze stops criminals from opening accounts in your name. Takes 10 minutes per bureau online; unfreeze anytime you need a loan.", a18:1},
 {h:"Opt out of overdraft 'protection'", d:"A declined card costs nothing and a moment of embarrassment. An overdraft 'courtesy' costs ~$35 per slip. Decline beats fee.", a18:1},
 {h:"Store credit cards: do the math", d:"10% off today, 25–30% interest forever after. One carried balance erases years of discounts. The cashier gets a bonus; you get the trap.", a18:1},
 {h:"A raise never hurts you at tax time", d:"Tax brackets are marginal: only the dollars ABOVE each line are taxed at the higher rate. 'The raise put me in a higher bracket so I take home less' is a myth. Always take the raise.", a18:1},
 {h:"A big tax refund isn't a bonus", d:"It's your own money, returned without interest, after a year-long free loan to the government. Adjusting your withholding gives you that money every paycheck instead.", a18:1},
 {h:"The HSA is a secret weapon", d:"If you have a high-deductible health plan: money goes in untaxed, grows untaxed, and comes out untaxed for medical costs. No other account does all three.", a18:1},
 {h:"Changing jobs? Don't cash the 401(k)", d:"Cashing out triggers taxes plus a 10% penalty — and robs your future self. Roll it into your new plan or an IRA. It's one form.", a18:1},
 {h:"A car's real price is four numbers", d:"Payment + insurance + fuel + repairs. The dealer shows you one of them. Total should stay under about 15–20% of take-home pay.", a18:1},
 {h:"Homes cost 1% a year to keep", d:"Budget roughly 1% of your home's value yearly for maintenance. The water heater doesn't care that this month was tight.", a18:1},
 {h:"Good debt builds, bad debt bleeds", d:"Debt that buys an appreciating future (education, a sane mortgage) can be a tool. Debt for things that lose value the moment you buy them is just expensive impatience.", a18:1},
 {h:"Know your market price", d:"Salary sites, job postings, and honest peers tell you what your work is worth. Companies know the number — negotiation only works if you do too.", a18:1},
 {h:"Side income: save 25–30% for taxes", d:"Freelance and gig money arrives untaxed. The IRS still wants its share next April. Park a quarter of every payment in savings the day it lands.", a18:1},
 {h:"Insure catastrophes, not inconveniences", d:"Insurance exists for what would ruin you: health, liability, house, income. Phone cracks and toaster deaths? That's what the emergency fund is for.", a18:1},
 {h:"The three-quote rule", d:"Movers, roofers, mechanics, insurance — get three quotes for anything big. The spread will shock you, and 'shopping around' takes one evening.", a18:1},
 {h:"Cash loses a little every year", d:"Inflation quietly eats 2–3% of cash's buying power annually. Emergency fund: cash. Money you won't touch for 10+ years: invested.", a18:1},
 {h:"Sinking funds end 'surprise' bills", d:"Christmas, car registration, and vacations are not surprises — they have dates. Divide the cost by the months left, save monthly, smile in December.", a18:1},
 {h:"The monthly money date", d:"Couples: 20 minutes, once a month, statements open, no blame. Most money fights are really surprise fights — and this kills the surprises.", a18:1},
 {h:"Payday loans: emergency exit only — and it's not an exit", d:"~400% APR turns a $300 problem into a $900 one. A credit union, a payment plan, even a credit card beats it. Almost anything beats it.", a18:1},
 {h:"Teach kids with real money", d:"Lectures bounce off; a blown allowance sticks forever. Give kids small real money and full authority to fail with it. Cheapest tuition they'll ever pay."}
],

mind: [
 {h:"Name it to tame it", d:"Saying 'I'm feeling anxious about Friday' literally reduces the brain's alarm response. Unnamed feelings drive the car; named feelings ride in it."},
 {h:"The 2-minute rule", d:"If it takes under two minutes, do it now. For bigger things: shrink the start to two minutes ('put on running shoes'). Starting is the whole battle."},
 {h:"Habit stacking", d:"Bolt a new habit onto an existing one: 'After I pour coffee, I write one sentence in my journal.' The old habit becomes the reminder."},
 {h:"When-then planning", d:"'When I get to work, then I'll write the hard email first.' People who plan the when-and-where are 2–3x more likely to follow through. Vague intentions evaporate."},
 {h:"The spotlight effect", d:"You think everyone noticed your stumble. They didn't — they were busy worrying about their own. Everyone is the main character of a different movie."},
 {h:"Sunk cost fallacy", d:"Money and time already spent are gone whether you continue or not. 'I've already put so much in' is a reason to stop, not to keep digging."},
 {h:"Confirmation bias", d:"Your brain auto-collects evidence for what you already believe. Antidote: once a week, genuinely read one smart person who disagrees with you."},
 {h:"Losses hurt double", d:"Losing $50 feels about twice as bad as winning $50 feels good. Knowing this explains half of your weird decisions — and other people's."},
 {h:"The confidence curve", d:"Beginners feel like experts; experts feel like beginners (Dunning-Kruger). If you're certain you've mastered something quickly, that's the signal you haven't."},
 {h:"The power of 'yet'", d:"'I can't do this' closes a door. 'I can't do this YET' leaves it open. It sounds tiny. Brains take it literally."},
 {h:"Space your learning", d:"One hour a day for four days beats four hours once. The forgetting between sessions is the workout — re-remembering is what builds the muscle."},
 {h:"Test yourself — don't reread", d:"Rereading feels productive and isn't. Closing the book and recalling is what wires memory. Struggle is the point, not the problem."},
 {h:"Sleep is when saving happens", d:"Your brain files the day's learning during sleep. All-nighters are typing without hitting save."},
 {h:"Exercise is a mood drug", d:"For mild low moods, regular exercise performs comparably to medication in studies — with only good side effects. A walk is a dose."},
 {h:"The 3 gratitudes trick", d:"Writing three specific good things each night measurably lifts mood within weeks. Specific beats general: 'the way Sam laughed at lunch,' not 'my family.'"},
 {h:"'I get to' vs 'I have to'", d:"'I have to make dinner' vs 'I get to cook for people I love.' Same task, different chemistry. Reframing isn't lying — it's choosing which true thing to look at."},
 {h:"Box breathing", d:"In 4, hold 4, out 4, hold 4. Repeat four times. Used by soldiers and surgeons. It's a manual override switch for panic, installed in everyone, labeled in almost no one."},
 {h:"5-4-3-2-1 grounding", d:"Overwhelmed? Find 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste. It pulls your brain out of the spiral and back into the room."},
 {h:"Schedule your worrying", d:"Rumination loves an open calendar. Give worries a daily 15-minute appointment. When they show up early, tell them: '4 o'clock.' Absurd. Works."},
 {h:"Self-compassion outperforms self-criticism", d:"People who talk to themselves like a good coach recover from failure faster than people who self-flagellate. Beatings improve no one's performance — including yours."},
 {h:"You vs. their highlight reel", d:"You compare your behind-the-scenes with everyone else's edited trailer. Social media is a film festival, not a documentary."},
 {h:"Novelty is fuel", d:"Brains release dopamine for new things. Stale routine? Change anything: the route, the playlist, the desk. Small newness reboots attention."},
 {h:"Attention residue", d:"Every task-switch leaves mental sludge from the last task — full focus takes ~20 minutes to return. Five 'quick checks' can wreck a whole afternoon."},
 {h:"Multitasking is a myth", d:"It's rapid task-switching, and it makes you worse at both things. Single-task the hard stuff; save multitasking for laundry and podcasts."},
 {h:"The recipe for flow", d:"Clear goal + slightly-too-hard challenge + zero interruptions = the state where hours vanish. You can't force flow, but you can set the table for it."},
 {h:"Parkinson's law", d:"Work expands to fill the time you give it. The report takes a week because you gave it a week. Try giving it two focused hours and watch."},
 {h:"Eat the frog", d:"Do the hardest, most-dreaded task first, while willpower is fresh. Everything after feels like dessert — and the dread stops poisoning your whole day."},
 {h:"Temptation bundling", d:"Only watch your show while folding laundry; only your favorite podcast while exercising. Chain a pleasure to a chore and the chore starts happening."},
 {h:"The fresh start effect", d:"Mondays, birthdays, first-of-the-month: humans genuinely change more easily at temporal landmarks. Don't mock New Year's resolutions — schedule more of them."},
 {h:"The peak-end rule", d:"Memory keeps two snapshots of any experience: the peak and the ending. End meetings, trips, and visits well — the ending colors the whole memory."},
 {h:"Showing up breeds liking", d:"The mere-exposure effect: familiarity itself creates fondness. New job, new gym, new neighborhood? Just keep appearing. Time does half the social work."},
 {h:"Give first", d:"Reciprocity is wired deep: people genuinely want to return favors. Generosity isn't just nice — it's how trust networks get built."},
 {h:"Repeat back before you reply", d:"'So you're saying the deadline moved and nobody told you?' People don't soften until they feel heard. This one habit upgrades every relationship you have."},
 {h:"Validate, then solve", d:"'That sounds really frustrating' must come BEFORE 'have you tried…' Skipping step one is why your great advice keeps starting fights."},
 {h:"Ask for the favor", d:"The Franklin effect: people like you MORE after doing you a small favor. Asking for help isn't imposing — it's how acquaintances become friends."},
 {h:"Small flaws make you likable", d:"The pratfall effect: competent people become MORE liked after a minor blunder. Perfection creates distance; spilled coffee creates friends. Relax."},
 {h:"Write the worst case down", d:"Vague dread is unbeatable; specific scenarios have solutions. 'If the worst happens, I would ___.' Fear hates paper."},
 {h:"Visualize the process, not the podium", d:"Imagining the victory feels great and changes nothing. Imagining the steps — the practice, the early alarm — measurably improves follow-through."},
 {h:"Journaling is RAM cleanup", d:"Your working memory keeps juggling open loops. Writing them down — tasks, fears, ideas — frees the mental tabs. Ten minutes of brain-dump beats an hour of stewing."},
 {h:"Protect some boredom", d:"Ideas incubate in idle moments — showers, walks, waiting rooms. Filling every gap with a phone starves your best thinking. Leave one gap unfilled today."},
 {h:"20 minutes of green", d:"Twenty minutes in a park or under trees measurably drops stress hormones. Nature is medicine that's free, unpatentable, and walking distance away."},
 {h:"The phone in the other room", d:"A visible phone — even face down, even OFF — measurably drains focus. Out of sight isn't discipline; it's physics."},
 {h:"Check news like mail, not like a slot machine", d:"Once or twice a day keeps you informed. Grazing all day keeps you anxious. The feed is engineered to never let you feel 'done' — so decide when you're done."},
 {h:"Savor for 30 seconds", d:"Good moment? Stay in it for 30 extra seconds — the taste, the light, the laugh. Savoring is how good moments become durable memories instead of blur."},
 {h:"Kindness pays the giver", d:"In study after study, doing something kind boosts the giver's happiness more than the receiver's. Generosity is self-care wearing a disguise."},
 {h:"Seek awe on purpose", d:"Big sky, vast ocean, great music, cathedral ceilings — awe shrinks the self and its worries. Schedule something bigger than you this month."},
 {h:"Be the noun, not the should", d:"'I'm trying to run more' loses to 'I'm a runner.' Identity-based habits stick because every action becomes a vote for who you are."},
 {h:"Design beats discipline", d:"Fruit on the counter gets eaten; cookies in the cupboard get forgotten. Don't strengthen your willpower — shorten the distance to good choices."},
 {h:"Write down open loops", d:"Unfinished tasks nag at your brain all day (the Zeigarnik effect) — but studies show just WRITING THE PLAN quiets the nagging. Your to-do list is a lullaby."},
 {h:"The 90-second rule", d:"The chemical wave of an emotion lasts about 90 seconds. Anything longer is the story you keep re-telling yourself about it. Feel the wave; question the rerun."}
],

world: [
 {h:"Why the sky is blue", d:"Sunlight contains all colors; air molecules scatter blue light the most, bouncing it across the whole sky. At sunset, light travels through more air — blue scatters away and red survives the trip."},
 {h:"How GPS knows where you are", d:"Your phone listens to precise clock signals from 4+ satellites and compares arrival times. The differences pin you down within meters. It's all clocks — your phone never transmits anything to the satellites."},
 {h:"How the internet actually travels", d:"Every message is chopped into tiny packets that race separately across the world — often by different routes — and reassemble at the destination. Most cross oceans through cables on the seafloor, not satellites."},
 {h:"How microwaves heat food", d:"The waves shake water molecules billions of times a second; that friction is the heat. It's why dry crackers stay cool, why edges cook first, and why stirring matters."},
 {h:"Refrigerators don't make cold", d:"Cold isn't a thing — it's the absence of heat. A fridge pumps heat from inside to the coils on the back. That's why the back of the fridge is warm: that's your leftovers' heat."},
 {h:"How planes stay up", d:"Wings are shaped and tilted to deflect massive amounts of air downward; pushing air down pushes the plane up. A jet's wings throw tons of air down every second."},
 {h:"Why huge steel ships float", d:"Floating is a weight contest: the ship versus the water it pushes aside. A hull full of air weighs less than that same volume of water — so the water wins, and pushes the ship up."},
 {h:"Why ice floats (and why it matters)", d:"Water is weird: it expands when it freezes, so ice is lighter than water. Lakes freeze top-down instead of bottom-up — which is the only reason fish survive winter."},
 {h:"How far is that lightning?", d:"Light arrives instantly; sound lags. Count seconds between flash and thunder, divide by 5 = miles away (by 3 = kilometers). Under 30 seconds? Get inside."},
 {h:"Why we have seasons", d:"Not distance — tilt. Earth leans 23.5° as it orbits, so each hemisphere takes turns leaning toward the sun. That's also why seasons are opposite in Australia."},
 {h:"Why tides happen", d:"The moon's gravity pulls the ocean into a bulge — and a matching bulge forms on the far side. Earth spins through both bulges daily: two high tides, two low."},
 {h:"What moon phases really are", d:"Half the moon is ALWAYS sunlit — phases are just our viewing angle changing as the moon orbits us. The 'dark side' gets exactly as much sun as the near side."},
 {h:"Satellites are always falling", d:"They're falling toward Earth constantly — but moving sideways so fast (~17,000 mph) that they keep missing. Orbit is permanent, perfectly-aimed falling."},
 {h:"Time zones follow the sun — roughly", d:"Each zone shifts the clock so noon stays near the sun's high point. Politics bends the lines: China spans five sun-hours but runs one official time."},
 {h:"Why leap years exist", d:"A year is really 365.25 days. Ignore the .25 and the calendar drifts — within centuries, July lands in winter. February 29 is the patch."},
 {h:"Daylight saving, decoded", d:"The sun doesn't move — we move the clock to shift daylight toward evening hours. Whether that's genius or madness is a fight every March and November."},
 {h:"How rainbows work", d:"Each raindrop is a tiny prism splitting sunlight into colors. You only see it with the sun BEHIND you — which is why you can never reach the end. Your rainbow is yours alone; everyone sees a slightly different one."},
 {h:"What the northern lights are", d:"Particles from the sun crash into our atmosphere, making the air itself glow — green from oxygen, purple-red from nitrogen. It's the sky working as a shield, visibly."},
 {h:"What thunder is", d:"Lightning heats air to ~30,000°C in a microsecond — five times hotter than the sun's surface. The air explodes outward; thunder is that shockwave reaching your ears."},
 {h:"Why earthquakes happen", d:"Continental plates creep constantly but their edges snag and stick. Stress builds for decades, then the snag slips all at once. The quake is the unstick."},
 {h:"Why the ocean is salty", d:"Rivers dissolve tiny amounts of mineral salt from rock and carry it seaward — for billions of years. Water escapes by evaporation; salt can't evaporate, so it stays and accumulates."},
 {h:"What makes bread rise", d:"Yeast is alive — billions of fungi eating sugar and burping CO2. The dough traps the bubbles; the oven sets them in place. Every loaf is a fossil of tiny breaths."},
 {h:"Fermentation is controlled rot", d:"Yogurt, cheese, beer, kimchi, sourdough, chocolate, coffee: all made by inviting the RIGHT microbes to transform food before the wrong ones can. Humanity's oldest biotechnology."},
 {h:"How soap actually works", d:"Each soap molecule has a water-loving head and a grease-grabbing tail. Tails harpoon the grime, water rinses the whole assembly away. Soap doesn't kill most germs — it evicts them."},
 {h:"What caffeine really does", d:"It doesn't add energy — it blocks the 'you're tired' signal (adenosine) from docking in your brain. The tiredness is still accumulating behind the blocked door. That's the afternoon crash."},
 {h:"Sunburn is radiation damage", d:"Not heat — UV radiation breaking DNA in your skin cells. The redness is your body's emergency repair response. You can burn badly on a cool, cloudy day."},
 {h:"How glasses fix vision", d:"A blurry eye focuses light slightly in front of or behind the retina. Lenses bend incoming light just enough to move the focal point onto the target. Precision-ground physics, sitting on your nose."},
 {h:"How batteries work", d:"A chemical reaction wants to happen, but the design forces its electrons to take the long way — through your device — to complete it. A battery is a chemical reaction held hostage, paying its way out in power."},
 {h:"The grid is a live balancing act", d:"Electricity is mostly used the instant it's made. Operators match supply to demand second by second, all day, every day. Big batteries are just beginning to change this."},
 {h:"How solar panels make power", d:"Sunlight is photons; in the panel, photons knock electrons loose, and loose flowing electrons ARE electricity. No moving parts — light goes in, current comes out."},
 {h:"Almost all power is spinning", d:"Coal, gas, nuclear, hydro, wind — nearly every power source is just a different way to spin a turbine in a magnetic field. Nuclear power is a very fancy water boiler. Solar is the odd one out."},
 {h:"What octane ratings mean", d:"Octane measures resistance to igniting too early — not power or quality. If your manual says regular, premium buys you nothing. The number protects high-compression engines; it doesn't upgrade yours."},
 {h:"ABS brakes: stomp and stay", d:"Anti-lock brakes pump themselves, far faster than any human foot. In an emergency: press hard and HOLD, even when the pedal shudders — that shudder is the system working."},
 {h:"Why roundabouts are safer", d:"A standard intersection has 32 ways for cars to collide, including deadly right angles and head-ons. A roundabout has 8, all glancing, all slow. Annoying? Sometimes. Safer? Massively."},
 {h:"Jet lag is a light problem", d:"Your body clock follows light, not your itinerary. The fix is the cause: get bright morning light at your destination, dim evenings, and the clock resets about an hour per day."},
 {h:"What inflation actually is", d:"More money chasing the same amount of goods bids prices up. A little (around 2%) is considered healthy oil for the economy; a lot is a tax on everyone's savings at once."},
 {h:"Supply and demand, the master dial", d:"Scarce + wanted = expensive. Abundant + unwanted = cheap. Concert tickets, houses, gas prices, surge pricing — once you see it, you see it everywhere, forever."},
 {h:"A stock is a slice of the pie", d:"One share = one tiny piece of actual ownership in a real company, with a claim on its future profits. The price is the world's live, lurching guess at what that future is worth."},
 {h:"Insurance is organized luck-sharing", d:"Thousands pay a small premium; the unlucky few collect big payouts. You're not 'wasting' premiums when nothing goes wrong — you're buying the certainty that disaster can't bankrupt you."},
 {h:"How banks make money on 'free' accounts", d:"Your deposits don't sit in a vault — banks lend them out at higher interest than they pay you. Your checking account is raw material. (Deposit insurance is why this isn't scary.)"},
 {h:"The truth about recycling", d:"Aluminum and cardboard recycle beautifully, almost forever. Most plastic doesn't — it downgrades once, maybe, then lands in the trash anyway. The real ranking: reduce, reuse, THEN recycle."},
 {h:"Compost is microbe farming", d:"Scraps + air + moisture = billions of microbes eating your banana peel into rich soil. Done right it smells like forest floor, not garbage — the smell means the recipe's off, not the idea."},
 {h:"How tap water gets clean", d:"Settle the big stuff, filter the small stuff, disinfect the living stuff — then test it constantly. In most developed countries, tap water is tested far more often than bottled."},
 {h:"Vaccines: a wanted poster", d:"A vaccine shows your immune system a harmless mugshot of the enemy. When the real thing arrives, your defenses already know its face. The training is the soreness; the memory lasts years."},
 {h:"Why antibiotic misuse matters to you", d:"Every unnecessary course teaches bacteria what our weapons look like. Superbugs aren't a future monster — they're evolution doing its job. Take antibiotics exactly as prescribed, never for colds."},
 {h:"Why metal sparks in the microwave", d:"Microwaves push electrons around; in metal, they pile up at points and edges until they leap through the air as sparks. The crinkles in foil are a stadium of tiny lightning bolts."},
 {h:"Echoes are how some animals 'see'", d:"Sound bounces off surfaces and returns; the delay maps the distance. Bats and dolphins build entire 3D pictures this way — and submarines' sonar is us copying their homework."},
 {h:"A mirage is bent light", d:"Hot air near the ground bends light from the sky upward into your eye — your brain interprets shimmering sky-light on the road as water. The 'puddle' is a reflection of the sky, retreating forever."},
 {h:"Volcanoes are pressure valves", d:"Molten rock is lighter than solid rock, so it rises, collecting in chambers under growing pressure. Eruptions are the planet venting. The scariest volcanoes are the quiet ones with sealed lids."},
 {h:"Why old windows ripple", d:"Old glassmaking left uneven panes — installers put the thick edge down. (Glass doesn't actually flow over centuries; that's a myth.) The ripple is a fingerprint of how it was made, not how it aged."}
],

challenge: [
 {c:"Drink a full glass of water within 10 minutes of waking", y:"You wake up mildly dehydrated every day — this is the cheapest energy boost that exists."},
 {c:"Text one old friend you haven't talked to in months", y:"Friendships die of silence, not conflict. One text is a defibrillator."},
 {c:"Set a timer for 10 minutes and declutter one surface", y:"Visual clutter is cognitive clutter. One clear counter calms a whole room."},
 {c:"Give three genuine, specific compliments today", y:"Specific beats generic: 'you explained that perfectly' lands; 'nice job' evaporates."},
 {c:"Eat one full meal with zero screens", y:"You'll taste the food, finish when you're full, and maybe even talk to someone."},
 {c:"Take the stairs every chance you get today", y:"Stair climbing is secretly one of the best leg and heart workouts hiding in your day."},
 {c:"Learn one neighbor's name (and use it)", y:"Neighborhoods are safety nets woven one name at a time."},
 {c:"Write down three things that went well today, and why", y:"This tiny exercise measurably raises happiness within two weeks. Tonight's the night."},
 {c:"Walk outside for 20 minutes — no podcast, no calls", y:"Unplugged walking is where your brain untangles its knots."},
 {c:"Cook tonight instead of ordering", y:"Saves ~$20, teaches your hands something, and tastes better than you expect."},
 {c:"Floss tonight", y:"Your gums are connected to your heart health. Two minutes, big returns."},
 {c:"Do 10 push-ups and 10 squats sometime today", y:"The minimum effective dose still counts. Strength is built in deposits this small."},
 {c:"Read 10 pages of any book", y:"10 pages a day is 15 books a year. You become what you repeatedly read."},
 {c:"Spend zero unnecessary dollars today", y:"A no-spend day resets the autopilot between wanting and buying."},
 {c:"Spend 10 minutes clearing your email inbox", y:"Every unread email is a tiny open loop in your head. Close some."},
 {c:"Back up your phone photos right now", y:"Phones drown, fall, and vanish. Memories shouldn't go with them."},
 {c:"Test your smoke alarm today", y:"Press one button, hear one beep, sleep easier for months. Dead batteries cause real tragedies."},
 {c:"Drink water before your coffee", y:"Hydrate first and the caffeine works better — and you start the day 1-0."},
 {c:"Stretch for 5 minutes before bed", y:"Evening stretching tells your nervous system the day is over. Better sleep, looser morning."},
 {c:"Call — actually call — someone you love", y:"Voices carry what texts can't. Two minutes of 'just thinking about you' beats 50 emojis."},
 {c:"Write tomorrow's to-do list tonight", y:"Your brain stops rehearsing tasks once they're on paper — and tomorrow starts itself."},
 {c:"Find three things to donate", y:"Someone needs what you're storing. Lighter closet, lighter mind."},
 {c:"Try one food you've never eaten", y:"Taste adventures keep your brain flexible and your dinners interesting."},
 {c:"Memorize one important phone number", y:"If your phone died right now, who could you actually call from memory?"},
 {c:"Go the whole day without complaining once", y:"Notice how often it almost slips out. That awareness is the real exercise."},
 {c:"Sit quietly for 5 minutes and just breathe", y:"Five minutes of stillness is a system reboot. No app required."},
 {c:"Write down one goal and the very first step", y:"Goals without a written first step stay dreams. Ink makes them projects."},
 {c:"Unsubscribe from 5 email lists", y:"Each one is a tiny recurring tax on your attention. Cancel the tax."},
 {c:"Park far away (or get off one stop early) on purpose", y:"Sneaky extra steps are the easiest exercise: no gym, no outfit, no excuse."},
 {c:"Check your posture every time you walk through a doorway", y:"Doorframes make perfect free reminders. Shoulders back, head tall, repeat all day."},
 {c:"Learn one keyboard shortcut you'll use forever", y:"Ten seconds to learn, saved a thousand times. Start with Ctrl+Z — undo in almost everything."},
 {c:"Thank someone for something specific they did a while ago", y:"Late gratitude hits harder — it means you're still thinking about it."},
 {c:"Make your bed within 5 minutes of getting up", y:"Win the first task of the day and the second one comes easier."},
 {c:"Balance on one foot for 30 seconds per side", y:"Balance quietly fades for decades, then matters enormously. Practice is prevention."},
 {c:"Do one kind thing for a stranger today", y:"Hold the door, pay a toll, leave the good parking spot. Kindness boosts the giver most."},
 {c:"No screens for the last 30 minutes before bed", y:"Your sleep hormone needs darkness to rise. Give it a head start tonight."},
 {c:"Move $5 to savings right now", y:"The amount isn't the point — keeping the muscle warm is."},
 {c:"Read your last credit card statement line by line", y:"Forgotten subscriptions and weird charges hide in plain sight. Go find them."},
 {c:"Smile and make eye contact with five strangers", y:"Micro-connections with strangers measurably lift mood — yours and theirs."},
 {c:"Deep-clean one drawer, completely", y:"One finished drawer beats six half-organized rooms. Total victory, tiny battlefield."},
 {c:"Take one photo of something genuinely beautiful today", y:"Hunting for beauty trains your eyes to find it everywhere. The photo is just proof."},
 {c:"Handwrite a short note to someone and deliver or mail it", y:"In a world of pixels, paper is luxury. Five sentences will be kept for years."},
 {c:"Learn to say 'thank you' in three new languages", y:"Gratitude is the best first word in any language. (Gracias, merci, arigatô — now find three more.)"},
 {c:"Stand up from a chair 10 times, no hands", y:"Sit-to-stand strength decides independence in old age. Bank some now."},
 {c:"Water your plants — or go buy one plant", y:"Caring for something green is tiny, daily proof that your attention makes things grow."},
 {c:"Book the appointment you've been putting off", y:"Doctor, dentist, haircut, oil change — two minutes of scheduling ends weeks of low-grade guilt."},
 {c:"Say no to one thing you don't actually want to do", y:"Every no is a yes to something that matters more. Practice the polite decline."},
 {c:"Go to bed 30 minutes earlier tonight", y:"Sleep is the legal performance enhancer. Tonight, take the upgrade."},
 {c:"Plan one small adventure for this weekend", y:"Anticipation is half the joy of any experience — schedule some to look forward to."},
 {c:"Tell someone exactly what they mean to you", y:"Don't save the good words for speeches and funerals. Spend them while they count."}
]
};

// Pillar-specific skill cards — shown when the user's guide matches
const PILLAR_SKILLS = {

// ── BEAVER (Buck) — Money & saving ──
beaver:[
 {e:"💰",t:"Build your first real budget",why:"Most people spend first and wonder where it went. A budget tells your money where to go before it disappears.",steps:["List every monthly income source and add them up","List every fixed expense (rent, phone, subscriptions)","Subtract — what's left is what you actually have to work with"]},
 {e:"🏦",t:"Open a separate savings account",why:"Mixing savings with spending money is how savings get spent. A separate account creates a mental wall.",steps:["Search your bank's app for 'savings account' and open one in 2 minutes","Set the nickname to your goal (e.g. 'Emergency Fund')","Move even $5 in today to make it real"]},
 {e:"📉",t:"Cut one subscription you forgot you had",why:"The average person pays for 3-4 subscriptions they rarely use. That's $30-80/month leaking out silently.",steps:["Open your bank or card statement and scan for recurring charges","Find one you haven't used this month","Cancel it right now — not later"]},
 {e:"🎯",t:"Set a 30-day savings target",why:"Vague goals don't get saved for. A number with a deadline does.",steps:["Pick a specific amount — even $50 is a win","Write the target and today's date somewhere visible","Set a phone reminder for 30 days from now to check in"]},
 {e:"💳",t:"Understand your credit score",why:"Your credit score controls whether you get an apartment, loan, or good interest rate. Most people never look at it.",steps:["Check it free at Credit Karma or your bank's app (no card needed)","Note whether it's poor/fair/good/excellent and the top reason it's not higher","Pick one action: pay a bill on time or lower a balance"]},
 {e:"🛒",t:"Try the 24-hour rule before buying",why:"Most impulse buys feel stupid the next day. Waiting 24 hours kills 80% of them.",steps:["Next time you want something that's not a necessity, put it in your cart but don't buy","Wait exactly 24 hours","If you still want it and can afford it, buy it — otherwise close the tab"]},
 {e:"📦",t:"Meal prep once a week",why:"Eating out 5x a week costs $200-400/month. Cooking the same meals at home costs $60-80.",steps:["Pick one day (Sunday works for most people)","Cook one big protein, one grain, two vegetables","Portion into containers — your lunches are done for the week"]},
 {e:"💡",t:"Find one bill you can lower",why:"Most people pay whatever they're billed without negotiating. Companies count on this.",steps:["Pick your internet, insurance, or phone bill","Call and say: 'I'm thinking of switching providers — what can you do for me?'","If they offer nothing, get a competitor quote and call back"]},
 {e:"🪣",t:"Start an emergency fund",why:"Without 3 months of expenses saved, one car repair or medical bill can spiral into debt.",steps:["Calculate your bare-minimum monthly expenses (rent + food + bills)","Multiply by 3 — that's your target","Open a separate account and start with whatever you can, even $20"]},
 {e:"📊",t:"Track every expense for one week",why:"Awareness is the first step. You can't fix what you don't see.",steps:["Use your phone's notes app or a free app like Mint","Log every purchase, even coffee","At the end of 7 days, add up each category and see what surprises you"]},
 {e:"🔄",t:"Automate one savings transfer",why:"Willpower runs out. Automation doesn't. Pay yourself first before you can spend it.",steps:["Log into your bank's app","Set up an automatic transfer of any amount to savings on payday","Start small — $10/week adds up to $520 a year"]},
 {e:"🏷️",t:"Learn the difference between needs and wants",why:"Not knowing the difference is why most people feel broke — even with decent income.",steps:["List your last 10 purchases","Mark each N (need) or W (want) honestly","Look at the pattern — your wants aren't bad, but they should be planned for"]},
 {e:"💸",t:"Pay off your smallest debt first",why:"The 'snowball method' — eliminating small debts first — builds momentum and reduces the mental weight of owing.",steps:["List all your debts and their balances","Pay minimums on all but the smallest","Throw every extra dollar at the smallest until it's gone, then roll that payment to the next"]},
 {e:"📱",t:"Delete shopping apps for one week",why:"Apps are designed to make spending frictionless. Remove the friction and watch your impulse spending drop.",steps:["Delete Amazon, ASOS, or whatever your weakness is — just for 7 days","Notice what you reach for your phone to buy and don't","Reinstall after a week if you want, but you'll shop differently"]},
 {e:"🧾",t:"Understand what you're actually paying in fees",why:"Bank fees, ATM fees, overdraft fees — they're small, but they add up to hundreds a year.",steps:["Log into your bank account and look at the last 3 months of fees","Add them up — most people are shocked","Switch to a no-fee account or change one habit to eliminate the biggest fee"]}
],

// ── WOLF (Coach) — Health & fitness ──
wolf:[
 {e:"🏃",t:"Walk 10 minutes every single day",why:"Consistency beats intensity. A daily 10-minute walk improves cardiovascular health, mood, and energy more than an occasional long run.",steps:["Pick a time that's already in your day — after lunch, before dinner","Put your shoes by the door as a trigger","Walk outside, not on a treadmill — the scenery change matters"]},
 {e:"💧",t:"Drink water before every meal",why:"Most people are chronically slightly dehydrated, which they feel as fatigue, poor focus, and fake hunger.",steps:["Put a glass of water next to wherever you eat","Drink it before touching your food","Do this for 7 days and notice the difference in your hunger levels"]},
 {e:"😴",t:"Fix your sleep in one step",why:"One bad sleep habit usually causes most sleep problems. Identifying it is the whole battle.",steps:["Write down what time you actually go to bed and wake up this week","Notice the biggest inconsistency (late nights, screens, caffeine after 3pm)","Fix just that one thing for 7 days"]},
 {e:"🥗",t:"Add vegetables — don't subtract anything",why:"Telling yourself to eat less of what you enjoy fails. Adding good things crowds out the bad naturally.",steps:["Add a handful of vegetables to one meal per day this week","Don't change anything else","After 2 weeks, add a second meal — the habit builds itself"]},
 {e:"🧘",t:"Try a 5-minute stretch routine",why:"Tight muscles cause poor posture, back pain, and injury. Five minutes of stretching daily makes a measurable difference in 2 weeks.",steps:["Stand up right now","Touch your toes (or try), hold 20 seconds","Roll your neck slowly each direction, then roll your shoulders — done"]},
 {e:"❤️",t:"Know your basic health numbers",why:"Blood pressure, resting heart rate, and weight are your body's vital signs. You can't manage what you don't measure.",steps:["Check your resting heart rate (60bpm = fit; 80+ = work to do)","If you haven't had a checkup in 2 years, book one today","Note your numbers — check again in 90 days"]},
 {e:"🏋️",t:"Do 10 push-ups every morning",why:"Upper body strength predicts longevity better than almost any other marker. Start tiny and let it grow.",steps:["Get on the floor the moment your alarm goes off","Do 10 push-ups — or as many as you can (even 3 counts)","That's it. Tomorrow do the same. Add one per week."]},
 {e:"🍽️",t:"Eat slower — actually chew",why:"Your brain takes 20 minutes to register fullness. Eating fast means you've overeaten before your body knows it.",steps:["Put your fork down between bites","Chew each bite at least 15 times","Try eating one meal today with no screen — just taste your food"]},
 {e:"🚫",t:"Cut ultra-processed food for one week",why:"Ultra-processed foods (chips, packaged snacks, fast food) are engineered to override your body's fullness signals.",steps:["Identify your top 2 processed food habits","Replace one with a whole-food version this week","Just one — not a complete overhaul"]},
 {e:"🌞",t:"Get outside in the first hour of waking",why:"Morning light resets your circadian rhythm, improves sleep at night, and gives your mood a real lift.",steps:["Tomorrow, step outside within 60 minutes of waking","Even 5 minutes on your porch or a short walk counts","No sunglasses for those first minutes — let the light hit your eyes"]},
 {e:"🧠",t:"Exercise for your brain, not your body",why:"People who exercise for mood and energy consistency stick to it. People who exercise for looks often quit.",steps:["After your next workout, write one word about how you feel mentally","Track this for a week — you'll build a new association","Let the mental benefit become your main reason"]},
 {e:"⏰",t:"Add movement to something you already do",why:"You don't need extra time in your day. You need to layer movement onto what already happens.",steps:["Pick one daily anchor: morning coffee, TV show, phone calls","Add movement to it — walk while on the phone, do squats during ads","Don't add new time — just improve existing time"]},
 {e:"💪",t:"Learn the plank",why:"The plank builds core strength that protects your lower back, improves posture, and takes 30 seconds.",steps:["Get into push-up position but on your forearms","Hold your body in a straight line — don't let your hips sag","Hold 20 seconds today. Add 5 seconds every 3 days."]},
 {e:"🫁",t:"Practice deep breathing once a day",why:"Shallow chest breathing keeps your stress system activated. Deep breathing through your nose resets it.",steps:["Breathe in through your nose for 4 counts","Hold for 4 counts","Breathe out through your mouth for 6 counts — do this 5 times"]},
 {e:"📏",t:"Track one health habit for 30 days",why:"What gets measured gets improved. You don't need an app — a checkmark on a calendar works.",steps:["Pick one habit: steps, water, sleep, push-ups","Put a checkmark on a physical calendar every day you do it","After 30 days, the chain itself motivates you not to break it"]}
],

// ── CAT (Momo) — Focus & mental calm ──
cat:[
 {e:"🧘",t:"Try a 2-minute breathing reset",why:"Two minutes of slow breathing activates the parasympathetic nervous system and physically lowers your stress response.",steps:["Breathe in for 4 counts through your nose","Hold for 2 counts","Breathe out for 6 counts — longer exhale is the key","Repeat 4 times — that's 2 minutes"]},
 {e:"📵",t:"Phone-free first 30 minutes",why:"Checking your phone immediately on waking puts your brain in reactive mode for the entire day.",steps:["Set your phone to Do Not Disturb and leave it face-down tonight","Tomorrow morning, don't touch it for 30 minutes","Use that time for anything else — coffee, stretching, quiet"]},
 {e:"🎯",t:"Pick just 3 priorities for today",why:"Long to-do lists create anxiety without clarity. Three things is a day that can actually succeed.",steps:["Write tomorrow's 3 most important tasks tonight","Do the hardest one first in the morning when your brain is fresh","Everything else is bonus — not failure if it doesn't happen"]},
 {e:"🌊",t:"Notice your thoughts without judgment",why:"Most anxiety comes from fighting your thoughts. Watching them like clouds passing changes your relationship to them.",steps:["Set a 3-minute timer","Close your eyes and notice whatever thoughts appear","Don't push them away — just name them: 'worry,' 'memory,' 'planning'","When the timer ends, open your eyes and carry on"]},
 {e:"📓",t:"Brain dump before bed",why:"Lying awake with thoughts racing usually happens because your brain is afraid of forgetting things. Writing them down releases that duty.",steps:["Keep a notepad by your bed","Before sleep, write everything on your mind — worries, tasks, ideas","Tell yourself: it's written, you won't forget it — now rest"]},
 {e:"🔕",t:"Schedule one hour of deep focus",why:"Constant notifications train your brain into shallow attention. Deep focus is a skill — you have to practice it deliberately.",steps:["Pick a task that requires real thinking","Set your phone to airplane mode for 60 minutes","Work only on that one task — when the hour ends, you've done real work"]},
 {e:"🏃",t:"Move your body when your mind spirals",why:"Anxiety lives in the body as tension. Physical movement is one of the fastest ways to discharge it.",steps:["When you feel your thoughts looping, stand up","Walk fast, do jumping jacks, shake your hands — anything physical","After 3-5 minutes of movement, your nervous system resets"]},
 {e:"🌿",t:"Create a calming anchor",why:"Your brain learns by association. A consistent sensory cue (smell, touch, sound) can trigger calm on demand.",steps:["Pick a scent (candle, lotion), a song, or a physical object","Use it only in calm moments for two weeks","Over time, encountering it will start to trigger that calm state"]},
 {e:"🗣️",t:"Talk to yourself like a friend",why:"The voice inside your head is often crueler than you'd ever be to someone you care about. Changing that changes everything.",steps:["Next time you make a mistake, notice the first thing you tell yourself","Ask: would I say this to my best friend in this situation?","Replace it with what you'd actually say to them"]},
 {e:"⏸️",t:"Build a micro pause habit",why:"Stress compounds when we never stop. A 60-second pause between tasks resets your nervous system and improves focus.",steps:["Between every task today, pause for 60 seconds","Don't fill it — just sit, breathe, look out a window","One minute of nothing is not wasted time — it's maintenance"]},
 {e:"😤",t:"Learn to name your emotions",why:"Research shows that naming an emotion reduces its intensity — a process called 'affect labeling.'",steps:["When you feel something uncomfortable, stop and name it precisely","Not just 'bad' — try: frustrated, ashamed, lonely, overwhelmed","The more specific the name, the faster the feeling loses its grip"]},
 {e:"🛑",t:"Set a hard stop time each day",why:"Without a defined end time, work and stress bleed into your rest. Your brain never gets the signal that it's safe to relax.",steps:["Pick a time tonight — say 8pm — as your 'work done' moment","When it arrives, close your laptop and put your phone down","Protect that boundary — it's what makes the next day possible"]},
 {e:"🤲",t:"Practice gratitude for 2 minutes",why:"Your brain has a negativity bias — it's wired to notice threats. Gratitude actively rewires it toward what's working.",steps:["Tonight, write 3 specific things that went okay today — not grand, just real","Not 'I'm grateful for my family' — try 'the coffee was exactly right this morning'","Specific beats general every time"]},
 {e:"💬",t:"Reach out to one person today",why:"Loneliness is one of the biggest drivers of anxiety and low mood. Connection is medicine — and it takes two minutes.",steps:["Think of one person you haven't talked to in a while","Send a message with no agenda — a meme, a memory, a quick 'thinking of you'","You don't need a reason. The message is the reason."]},
 {e:"🌙",t:"Design a wind-down routine",why:"You can't switch from full-speed to asleep. A 20-minute buffer signals your brain that the day is done.",steps:["Pick 3 simple wind-down actions: dim lights, herbal tea, reading","Do them in the same order every night for 2 weeks","Your brain will start producing melatonin automatically as the routine begins"]}
],

// ── LION (Leo) — Confidence & courage ──
lion:[
 {e:"🦁",t:"Do one thing that scares you today",why:"Confidence isn't something you have before you act — it's what you build by acting. Every small scary thing makes the next one smaller.",steps:["Think of one thing you've been avoiding out of fear","Make it small enough to do today (not 'quit my job' — 'send the email')","Do it before noon while your willpower is strongest"]},
 {e:"🪞",t:"Fix your posture right now",why:"Studies show standing tall actually changes how you feel about yourself — the body leads the mind, not the other way around.",steps:["Stand up from wherever you are","Feet shoulder-width, shoulders back, chin parallel to the floor","Take 3 deep breaths in this position — notice the shift"]},
 {e:"🗣️",t:"Speak up once in a group today",why:"Every time you stay quiet when you have something to say, you reinforce the belief that your voice doesn't matter.",steps:["In the next group setting — meeting, conversation, class — say one thing","It doesn't have to be profound. Asking a question counts.","The goal is to break the silence habit, not to impress anyone"]},
 {e:"✅",t:"Keep one promise to yourself",why:"Self-trust is built the same way as trust with others — by doing what you say you'll do. Break promises to yourself and your confidence erodes.",steps:["Make one small promise to yourself this morning (drink water, go for a walk, make the call)","Do it — exactly as promised, not a scaled-down version","Notice how it feels to follow through. That feeling is confidence."]},
 {e:"🏆",t:"Write down 3 things you're actually good at",why:"Most people can list their flaws immediately but go blank on their strengths. You have real ones — they deserve naming.",steps:["Sit quietly for 5 minutes","Write 3 things you genuinely do well — skills, traits, or moments you handled something right","Read the list out loud — uncomfortable at first, but that's the work"]},
 {e:"👀",t:"Make eye contact and hold it",why:"Eye contact is one of the clearest signals of confidence in every culture. Most people with low confidence break it first.",steps:["In your next conversation, focus on keeping eye contact a little longer than feels natural","When the discomfort comes, don't look away — breathe through it","After a week of practice, it becomes natural"]},
 {e:"🚫",t:"Say no without apologizing",why:"Over-apologizing for your limits teaches others that your limits aren't real. A clear no is more respectful than a sorry-yes.",steps:["Today, when you want to decline something, say 'No, I can't do that'","Don't add 'sorry' unless you've actually done something wrong","Notice the other person's reaction — most will respect it immediately"]},
 {e:"📣",t:"Share an opinion you'd normally keep quiet",why:"People pleasers disappear — literally, they become unreadable. Sharing a real opinion makes you memorable and respected.",steps:["In the next conversation, when someone asks what you think, actually say it","Keep it honest and direct — 'I think X because Y'","You don't have to convince anyone. Just say the actual thing."]},
 {e:"💌",t:"Celebrate a recent win — for real",why:"Your brain is wired to minimize your achievements and amplify your failures. Deliberately celebrating rebalances that.",steps:["Think of something good you did this week — even small","Tell one person about it — not bragging, just sharing","Then do something small to mark it: good meal, nice walk, a purchase you've been delaying"]},
 {e:"🎤",t:"Practice talking out loud to yourself",why:"Athletes, speakers, and performers all use self-talk deliberately. It's not weird — it's training.",steps:["When alone, narrate what you're doing or talk through a problem out loud","Practice saying confident statements out loud: 'I can handle this'","The more you hear yourself speak confidently, the more your brain believes it"]},
 {e:"🤝",t:"Introduce yourself first",why:"Waiting for others to introduce themselves is a passive habit. Going first takes courage and immediately sets a tone of confidence.",steps:["In the next social situation where you don't know someone, go first","Extend your hand, say your name clearly, ask one question","You control the first impression when you initiate"]},
 {e:"📝",t:"Write your own definition of success",why:"Most people chase other people's definitions of success and feel empty when they get there. Your version has to be yours.",steps:["Write: 'Success for me means...' and finish it honestly","Cross out anything that sounds like it came from your parents, social media, or someone else","Read what's left — that's your actual direction"]},
 {e:"⚡",t:"Act before you feel ready",why:"Waiting until you feel confident is backwards — action creates confidence, not the other way around.",steps:["Identify something you've been waiting until you're 'ready' for","Acknowledge you'll never feel 100% ready","Take the first step today — one imperfect action beats perfect preparation"]},
 {e:"🧱",t:"Handle one hard thing you've been avoiding",why:"Every thing you avoid grows into something heavier. Facing it shrinks it back down to actual size.",steps:["Name the one thing you've been putting off because it feels too hard","Break it into the smallest possible first step","Do just that first step today — you'll find it was smaller than your fear made it look"]},
 {e:"🌟",t:"Dress like you mean it today",why:"What you wear changes how you feel, and how you feel changes how you act. This isn't shallow — it's practical.",steps:["Put on something you feel good in — not comfortable, but good","Stand in front of a mirror for 30 seconds before you leave","Walk out the door carrying that feeling"]}
],

// ── EAGLE (Vera) — Career & leadership ──
eagle:[
 {e:"💼",t:"Update your resume right now",why:"Most people only update their resume when desperate. A current resume keeps your options open and reminds you of your own value.",steps:["Open your resume — or create one if you don't have one","Add the last 2 roles or achievements you haven't added yet","Save it as 'FirstName_LastName_Resume_2026.pdf' and keep it somewhere easy to find"]},
 {e:"🤝",t:"Reach out to one professional contact",why:"Most opportunities come through people, not job boards. Staying connected to your network is career maintenance.",steps:["Think of one former colleague, classmate, or mentor you haven't spoken to in 6+ months","Send a short message: 'Hey — thinking of you, hope things are good'","No agenda needed. Relationships are kept warm by simple contact."]},
 {e:"🎯",t:"Set one career goal for this year",why:"Vague ambitions don't become careers. One specific goal gives you something to aim at and measure against.",steps:["Write: 'By [date], I want to [specific achievement]'","Make it concrete — not 'get better at my job' but 'get promoted to senior by December'","Put it somewhere you'll see it weekly"]},
 {e:"📚",t:"Learn one skill relevant to your career",why:"The people who grow fastest in their careers are deliberate learners. Even 20 minutes a week compounds dramatically.",steps:["Identify one skill that would make you more valuable in your field","Find a free resource: YouTube, a podcast, a free course","Commit to 20 minutes this week — just this week"]},
 {e:"🗣️",t:"Ask for feedback you haven't been given",why:"Most managers won't volunteer feedback — you have to ask directly. The ones who ask grow faster than the ones who wait.",steps:["Ask your manager or a trusted colleague: 'What's one thing I could do better?'","Listen without defending — just thank them and take notes","Act on one piece of their feedback visibly, then follow up"]},
 {e:"📧",t:"Send a better email",why:"Clear, brief emails get read and acted on. Long ones get skimmed and ignored. This skill separates professionals.",steps:["Before sending your next email, read it once and cut it by 30%","Put the request or main point in the first sentence — not the third","Subject line should be a mini-summary, not a greeting"]},
 {e:"🏗️",t:"Identify your most valuable skill",why:"Knowing what makes you uniquely useful helps you position yourself, ask for raises, and make career decisions with clarity.",steps:["Ask: what do people come to me for that they don't go to others for?","Write it down plainly — 'I'm the person who can X'","Find one way to use or demonstrate that skill more visibly this week"]},
 {e:"⏰",t:"Protect your most productive hours",why:"Most people do shallow work (email, meetings, admin) in their peak mental hours and wonder why real work doesn't get done.",steps:["Identify when you're sharpest — most people: 9-11am","Block that time in your calendar with 'Deep Work — no meetings'","Spend it on the work that actually moves things forward"]},
 {e:"🧠",t:"Read one industry article this week",why:"Staying informed about your field takes 20 minutes and sets you apart from the majority who don't bother.",steps:["Subscribe to one newsletter or publication in your industry","Read one article this week — not skim, actually read","Note one thing you learned and could mention in a conversation"]},
 {e:"💬",t:"Run a better meeting",why:"Most meetings are longer than they need to be and end without clear next steps. One person who fixes this stands out instantly.",steps:["Before your next meeting, set a clear agenda and send it ahead of time","At the end, say: 'What are the action items and who owns each?'","End 5 minutes early — people will notice and love you for it"]},
 {e:"🌐",t:"Build your LinkedIn in 15 minutes",why:"Recruiters, clients, and collaborators check your LinkedIn before they check anything else. A sparse profile is a missed opportunity.",steps:["Add a professional photo if you don't have one — even a clean selfie","Write a one-sentence headline that says what you do and who you help","Add your 3 most recent roles with one bullet about what you actually achieved"]},
 {e:"🔍",t:"Research your market value",why:"Most people are paid what they negotiated years ago, not what they're worth now. Knowing the number changes everything.",steps:["Search Glassdoor, LinkedIn Salary, or Levels.fyi for your role and location","Note the range for your experience level","If you're below the midpoint, you have a data-backed reason to ask"]},
 {e:"🏅",t:"Mentor or help someone junior",why:"Teaching someone else is the fastest way to solidify your own knowledge — and leadership is noticed by people above you.",steps:["Think of one person who's newer in your field than you","Offer to answer one question or share one thing you know","You don't need to be an expert — just one step ahead counts"]},
 {e:"📈",t:"Track your wins in a 'brag doc'",why:"Performance reviews happen once a year but wins happen daily. Documenting them means you never struggle to articulate your value.",steps:["Create a document called 'My Wins'","Write down any positive feedback, completed project, or result you contributed to this week","Review it before any review, interview, or raise conversation"]},
 {e:"🚀",t:"Apply for something slightly out of reach",why:"Most people self-select out of opportunities before anyone else does. Applying to stretch roles is how careers accelerate.",steps:["Find a job, project, or role you want but feel slightly underqualified for","Apply or put your hand up — they'll tell you no if they want to","The worst case is you practice — the best case changes your life"]}
]

};

