// ============ CHRISTIAN MANUAL — DAILY KNOWLEDGE BANKS ============
// Each pool rotates daily. To add entries, APPEND to the end of a pool.
const DAILY = {

// ── VERSE OF THE DAY (shown as "Word of the Day" slot) ──────────────────────
// Format: w = word/topic label, d = verse text + reference, x = reflection sentence
vocab: [
 {w:"Strength", d:"\"I can do all things through Christ who strengthens me.\" — Philippians 4:13", x:"Not your own will — but strength drawn from someone who never runs out."},
 {w:"Love", d:"\"For God so loved the world that he gave his one and only Son.\" — John 3:16", x:"The most quoted verse in the Bible. Read it slowly today as if for the first time."},
 {w:"Peace", d:"\"The Lord is my shepherd; I shall not want.\" — Psalm 23:1", x:"Wanting nothing is not poverty — it's trust that the Shepherd provides."},
 {w:"Fear", d:"\"Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you.\" — Joshua 1:9", x:"God never commands courage without promising his presence."},
 {w:"Trust", d:"\"Trust in the Lord with all your heart and lean not on your own understanding.\" — Proverbs 3:5", x:"'With all your heart' means especially the parts that are afraid."},
 {w:"Grace", d:"\"For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.\" — Ephesians 2:8", x:"Grace means the gift was given before you earned it. Which means you can't lose it by failing to earn it."},
 {w:"Joy", d:"\"This is the day the Lord has made; let us rejoice and be glad in it.\" — Psalm 118:24", x:"Not 'if the day goes well' — this particular day, exactly as it arrives."},
 {w:"Worry", d:"\"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.\" — Philippians 4:6", x:"The instruction is not 'stop worrying.' It's: redirect worry into prayer."},
 {w:"Forgiveness", d:"\"Bear with each other and forgive one another if any of you has a grievance. Forgive as the Lord forgave you.\" — Colossians 3:13", x:"The standard is clear and high: as the Lord forgave you."},
 {w:"Renewal", d:"\"Do not conform to the pattern of this world, but be transformed by the renewing of your mind.\" — Romans 12:2", x:"Transformation is a process, not an event — and it starts in the mind."},
 {w:"Compassion", d:"\"The Lord is gracious and compassionate, slow to anger and rich in love.\" — Psalm 145:8", x:"Four qualities of God in one verse. Which one do you most need today?"},
 {w:"Fruit", d:"\"But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control.\" — Galatians 5:22–23", x:"Nine qualities, one source. Which is God growing in you right now?"},
 {w:"Serving", d:"\"Even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.\" — Mark 10:45", x:"Service is not beneath you. It was not beneath Jesus."},
 {w:"Humility", d:"\"Humble yourselves before the Lord, and he will lift you up.\" — James 4:10", x:"Humility is not thinking less of yourself — it's thinking of yourself less."},
 {w:"Prayer", d:"\"Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.\" — Matthew 7:7", x:"Three verbs: ask, seek, knock. All of them take action."},
 {w:"Courage", d:"\"Have I not commanded you? Be strong and courageous.\" — Joshua 1:9", x:"'Have I not commanded you?' — this is not a suggestion. God commands us toward courage."},
 {w:"Creation", d:"\"In the beginning God created the heavens and the earth.\" — Genesis 1:1", x:"Four words establish everything: In. The. Beginning. God."},
 {w:"Identity", d:"\"See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!\" — 1 John 3:1", x:"Your deepest identity is not what you do — it's whose you are."},
 {w:"Rest", d:"\"Come to me, all you who are weary and burdened, and I will give you rest.\" — Matthew 11:28", x:"Jesus offers rest to the weary. The only requirement is coming."},
 {w:"Hope", d:"\"For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.\" — Jeremiah 29:11", x:"Originally spoken to exiles in Babylon. God's plans persist even in your worst season."},
 {w:"Light", d:"\"Your word is a lamp for my feet, a light on my path.\" — Psalm 119:105", x:"A lamp shows the next step — not the whole road. Faith is enough light for today."},
 {w:"Righteousness", d:"\"But seek first his kingdom and his righteousness, and all these things will be given to you as well.\" — Matthew 6:33", x:"What you seek first shapes everything else you pursue."},
 {w:"Steadfast", d:"\"Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning.\" — Lamentations 3:22–23", x:"Written in the middle of catastrophe. New mercies come regardless of yesterday."},
 {w:"Faith", d:"\"Now faith is confidence in what we hope for and assurance about what we do not see.\" — Hebrews 11:1", x:"The Bible's own definition: confidence and assurance — not certainty, but trust."},
 {w:"Wisdom", d:"\"If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.\" — James 1:5", x:"God gives wisdom generously, without finding fault. You don't have to earn the right to ask."},
 {w:"Kindness", d:"\"Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.\" — Ephesians 4:32", x:"Kindness is grounded in what you've already received — not what you feel like giving."},
 {w:"Perseverance", d:"\"Let us run with perseverance the race marked out for us, fixing our eyes on Jesus.\" — Hebrews 12:1", x:"The race is marked out — meaning God has already mapped your path. Run it."},
 {w:"Generosity", d:"\"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.\" — 2 Corinthians 9:7", x:"Cheerful giving starts with decided giving. The decision comes before the feeling."},
 {w:"Truth", d:"\"Then you will know the truth, and the truth will set you free.\" — John 8:32", x:"Freedom comes from truth, not from comfort. What truth are you resisting today?"},
 {w:"Mercy", d:"\"Blessed are the merciful, for they will be shown mercy.\" — Matthew 5:7", x:"You receive the mercy you give. What does that make today's choices?"},
 {w:"Salvation", d:"\"For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.\" — Romans 6:23", x:"Two things: what we earn on our own, and what God gives anyway."},
 {w:"Obedience", d:"\"We know that we have come to know him if we keep his commands.\" — 1 John 2:3", x:"Knowledge of God is not just intellectual. It's confirmed by how you live."},
 {w:"Patience", d:"\"Be still before the Lord and wait patiently for him.\" — Psalm 37:7", x:"Stillness is not passivity — it's the discipline of trusting God's timing."},
 {w:"Unity", d:"\"How good and pleasant it is when God's people live together in unity!\" — Psalm 133:1", x:"Unity among believers is not just practical — Scripture calls it good and pleasant."},
 {w:"Mission", d:"\"Therefore go and make disciples of all nations.\" — Matthew 28:19", x:"The Great Commission uses one imperative: go. Everything else follows from movement."},
 {w:"Sanctification", d:"\"It is God's will that you should be sanctified.\" — 1 Thessalonians 4:3", x:"Sanctification is not self-improvement. It's allowing God to make you holy."},
 {w:"Sacrifice", d:"\"Greater love has no one than this: to lay down one's life for one's friends.\" — John 15:13", x:"The ultimate measure of love is not what you say — it's what you give up."},
 {w:"Worship", d:"\"God is spirit, and his worshipers must worship in the Spirit and in truth.\" — John 4:24", x:"Worship is not a style of music — it's the alignment of your spirit with God's truth."},
 {w:"Eternal", d:"\"For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.\" — John 3:16", x:"Eternal life begins now — in the quality of knowing God, not just in length of days."},
 {w:"Blessing", d:"\"Blessed is the one who does not walk in step with the wicked.\" — Psalm 1:1", x:"Biblical blessing begins with a negative — what you choose not to do shapes everything you become."},
 {w:"Covenant", d:"\"Know therefore that the Lord your God is God; he is the faithful God, keeping his covenant of love to a thousand generations.\" — Deuteronomy 7:9", x:"A thousand generations. God's faithfulness is not measured in moments but in millennia."},
 {w:"Redemption", d:"\"For he has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves.\" — Colossians 1:13", x:"You were rescued — past tense, already done. Live from that reality today."},
 {w:"Purpose", d:"\"For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.\" — Ephesians 2:10", x:"Your purpose was prepared before you arrived. Today you live into it."},
 {w:"Refuge", d:"\"God is our refuge and strength, an ever-present help in trouble.\" — Psalm 46:1", x:"Ever-present means he is not sometimes-present. He is there in the trouble itself."},
 {w:"Rebirth", d:"\"Therefore, if anyone is in Christ, the new creation has come: the old has gone, the new is here!\" — 2 Corinthians 5:17", x:"The past is not the predicate of the future. New creation means genuinely new."},
 {w:"Praise", d:"\"I will extol the Lord at all times; his praise will always be on my lips.\" — Psalm 34:1", x:"'At all times' includes the hard times. Praise in difficulty is the most powerful kind."},
 {w:"Intercession", d:"\"The Spirit himself intercedes for us through wordless groans.\" — Romans 8:26", x:"When you can't pray, the Spirit prays for you. You are never without an advocate."},
],

// ── BODY — Stewardship of the body as God's temple ──────────────────────────
body: [
 {f:"Your body is called a temple in Scripture — 'Do you not know that your bodies are temples of the Holy Spirit?' (1 Corinthians 6:19).", a:"Treat one act of physical care today as an act of worship, not vanity."},
 {f:"Jesus regularly withdrew to 'lonely places' to rest and pray (Luke 5:16). Rest was part of his rhythm.", a:"Build one genuine rest period into your day — not entertainment, but actual quiet."},
 {f:"Psalm 139 says you are 'fearfully and wonderfully made.' That's not a compliment — it's a theological statement.", a:"Write one specific thing your body does well that you usually take for granted."},
 {f:"God rested on the seventh day (Genesis 2:2–3). This is the first thing in Scripture called 'holy.'", a:"If you're worn out today, rest without guilt. You're following God's pattern, not breaking it."},
 {f:"Elijah collapsed under a tree after his greatest victory and asked to die (1 Kings 19:4). Then God gave him food and told him to sleep.", a:"Sometimes the most spiritual thing is a nap and a meal. Don't spiritualise burnout."},
 {f:"Daniel asked for vegetables and water instead of the king's food — and was healthier at the end (Daniel 1:12–15).", a:"Food choices are stewardship choices. One small swap toward whole food honours the body you've been given."},
 {f:"Your heart beats 100,000 times a day without you asking it to. The Psalmist calls this kind of sustained care 'the works of the Lord.'", a:"Thank God for something your body does automatically today. Gratitude changes how you inhabit it."},
 {f:"Studies show that people with strong faith communities live measurably longer — lower stress hormones, better immune function.", a:"Connection is not just nice. It's physical medicine. Reach out to one person in your faith community today."},
 {f:"Sleep deprivation affects moral decision-making — tired people are measurably less compassionate, more irritable, less able to resist temptation.", a:"Protecting your sleep is protecting your character. Aim for 7–8 hours tonight."},
 {f:"Paul says 'bodily training is of some value' (1 Timothy 4:8) — less than godliness, but real value nonetheless.", a:"A 20-minute walk is both good for your body and gives you time to pray or think. Combine them today."},
 {f:"Breath in Hebrew is 'ruach' — the same word used for Spirit. 'God breathed into his nostrils the breath of life' (Genesis 2:7).", a:"Take three slow, deep breaths right now and consider that breath as a connection to the God who gave it."},
 {f:"Jesus fasted for 40 days — but he also attended parties, ate with sinners, and turned water into wine at a wedding.", a:"Faith is not asceticism for its own sake. Enjoy food and celebration today without guilt."},
 {f:"Walking was Jesus's primary mode of transport and conversation. Most of his teaching happened on the move.", a:"On your next walk, instead of a podcast, try praying out loud or in your head as you go."},
 {f:"The body's stress response — cortisol, adrenaline — is designed for short bursts, not days on end. Chronic stress inflames the body at a cellular level.", a:"Name your biggest stressor today and bring it to God specifically: 'Lord, I'm carrying this.'"},
 {f:"Laughter reduces stress hormones, boosts immunity, and appears regularly in Scripture — even God is described as 'laughing' (Psalm 2:4).", a:"Watch or read something genuinely funny today. Joy is fruit of the Spirit, not frivolity."},
 {f:"The ancient practice of fasting has measurable physical benefits: reduced inflammation, improved insulin sensitivity, cellular repair.", a:"Even skipping one snack and spending that time in prayer is a beginning. Start where you can."},
 {f:"Sunlight triggers serotonin production — the same neurotransmitter that antidepressants target. 10–20 minutes of daylight is measurable medicine.", a:"Get outside today. Creation is good (Genesis 1:31) — being in it is an act of receiving that goodness."},
 {f:"Gratitude journalling measurably reduces blood pressure and improves sleep quality over time. This is the science behind 'give thanks in all circumstances' (1 Thessalonians 5:18).", a:"Write three specific things you're grateful for tonight before you sleep."},
 {f:"The gut — now called the 'second brain' — contains 90% of the body's serotonin and communicates directly with the brain. What you eat affects how you think and feel.", a:"Add one fibre-rich whole food today: beans, oats, an apple. It's stewardship of the body God gave you."},
 {f:"Hands laid on someone in Scripture signify blessing, healing, and commissioning. Physical touch is theologically significant — and scientifically validated for wellbeing.", a:"Give someone a genuine hug today. Fifteen seconds activates oxytocin in both of you."},
 {f:"Weeping is not weakness in Scripture. Jesus wept (John 11:35). David wept. The Psalms are full of tears.", a:"If you've been suppressing grief, give it some room today. Tears are not a faith failure."},
 {f:"Your brain is most creative and spiritually receptive in the drowsy moments just before sleep — the 'hypnagogic' state. Many believers report God speaking in these moments.", a:"Instead of scrolling before sleep, lie quietly and listen. Some of your best thoughts — and prayers — may come."},
],

// ── MONEY — Biblical stewardship & generosity ───────────────────────────────
money: [
 {h:"'The earth is the Lord's, and everything in it' (Psalm 24:1)", d:"This is the foundation of Christian stewardship. You don't own your money — you manage it for someone else. That changes every financial decision."},
 {h:"Bring the whole tithe", d:"Malachi 3:10 invites Israel to 'test God' with the tithe. It's the one place in Scripture God says to put him to the test. Have you tried it for three months?"},
 {h:"The love of money — not money itself", d:"1 Timothy 6:10 is often misquoted. It's the LOVE of money that's the root of all kinds of evil — not money itself. The problem is in the heart, not the bank account."},
 {h:"Contentment is learned", d:"Paul says 'I have learned, in whatever state I am, to be content' (Philippians 4:11). Contentment is not a feeling — it's a practiced skill."},
 {h:"Debt is a form of slavery", d:"Proverbs 22:7: 'The borrower is servant to the lender.' This doesn't mean debt is always sinful — but every debt reduces your freedom. Know the cost."},
 {h:"The rich young ruler's problem wasn't his wealth", d:"Jesus didn't tell everyone to sell everything — only this man, because his wealth had become his lord. The question is not how much you have but who sits on the throne."},
 {h:"Zacchaeus didn't give it all — and Jesus called it salvation", d:"Zacchaeus gave half his possessions and repaid fraud fourfold (Luke 19:8). Generosity doesn't require perfection — it requires a turning."},
 {h:"The widow's two coins outweighed the wealthy gifts", d:"Jesus said she gave more — not in amount but in proportion (Mark 12:43). God measures giving by what you kept, not what you gave."},
 {h:"Plan giving in advance — then give cheerfully", d:"2 Corinthians 9:7 says decide in your heart first, then give. Cheerfulness follows a decision. It doesn't have to precede it."},
 {h:"Save from a posture of trust, not fear", d:"Joseph stored grain for seven years of plenty to survive seven years of famine (Genesis 41). Saving is wisdom — but savings hoarded out of fear is a different thing."},
 {h:"Seek justice in your money, not just charity", d:"Amos repeatedly condemns dishonest scales and exploitation of the poor. Ethical spending, fair business, and just wages are stewardship issues."},
 {h:"The principle of enough", d:"Proverbs 30:8–9: 'Give me neither poverty nor riches, but give me only my daily bread.' There is a biblical vision of enough — not maximum accumulation."},
 {h:"Don't neglect the poor — it is not a suggestion", d:"Proverbs 19:17: 'Whoever is kind to the poor lends to the Lord.' Generosity to the poor is described in Scripture as a loan to God."},
 {h:"God sees financial injustice", d:"James 5:4: 'The wages you failed to pay the workers who mowed your fields are crying out against you.' Pay people fairly. Pay on time. It matters to God."},
 {h:"Make a plan — but hold it loosely", d:"Proverbs 16:9: 'In their hearts humans plan their course, but the Lord establishes their steps.' Budget, plan, and save — but stay open-handed."},
 {h:"Treasure in heaven is not metaphor", d:"Matthew 6:19–21: where your treasure is, your heart follows. Every kingdom investment is a reorientation of the heart, not just a financial transaction."},
 {h:"Be honest in all financial dealings", d:"Leviticus 19:35–36 commands honest scales. In any transaction — salary negotiation, tax return, expense claims — honesty is the non-negotiable."},
 {h:"Generosity breaks the power of money", d:"You cannot serve God and money (Matthew 6:24). Regular giving is not just obedience — it is a practical act of declaring who rules you."},
 {h:"The tithe: a beginning, not a ceiling", d:"Ten percent was given to the Levites who had no inheritance. In the New Testament, generosity often exceeds the tithe. Let the tithe be the floor, not the goal."},
 {h:"Rest from acquisition", d:"The Sabbath year (Leviticus 25) commanded land to rest and debts to be released every seven years. God's economy includes interruptions to the accumulation machine."},
],

// ── MIND — Spiritual disciplines & prayer ───────────────────────────────────
mind: [
 {h:"Lectio Divina: reading that listens", d:"Read a short Scripture passage four times slowly: first for the overall text, second for a word that stands out, third for what it says to your life, fourth in response to God. The same passage, four depths."},
 {h:"The SOAP method", d:"Scripture → Observation (what does it say?) → Application (what does it say to me?) → Prayer (what do I say to God in response?). Four steps, any passage, any morning."},
 {h:"Breath prayer", d:"A word or short phrase repeated on each inhale and exhale. Classic: 'Lord Jesus Christ' (inhale) / 'have mercy on me' (exhale). Ten minutes of this is ten minutes of quieting the inner noise."},
 {h:"Fasting: the forgotten discipline", d:"Jesus said 'when you fast' — not 'if.' Fasting is abstaining from something good to seek something better. Start with one meal. Use the hunger as a prompt to pray."},
 {h:"Silence and solitude", d:"Jesus 'withdrew to desolate places and prayed' (Luke 5:16). Silence is not the absence of God — it's clearing the noise so you can hear him. Even 10 minutes changes the day."},
 {h:"Intercessory prayer: carrying others to God", d:"Prayer for other people is one of the most powerful and least practiced disciplines. Name five people this week and pray for them daily by name — not a list, but a conversation."},
 {h:"Gratitude as spiritual practice", d:"'Give thanks in all circumstances' (1 Thessalonians 5:18) is a command, not a feeling. Writing three specific gratitudes tonight is both obedience and science-backed wellbeing practice."},
 {h:"Confessional prayer", d:"1 John 1:9 promises: 'If we confess our sins, he is faithful and just and will forgive us.' Unconfessed sin accumulates weight. Named and confessed sin loses its power."},
 {h:"The Daily Examen", d:"A Jesuit practice for every evening: Where did I feel God's presence today? Where did I resist it? What am I grateful for? What do I want to bring to tomorrow? Five minutes, enormous clarity."},
 {h:"Scripture memory: fighting with the right weapon", d:"Jesus answered every temptation in the wilderness with a memorised verse (Matthew 4). Scripture in the head becomes a sword in the hand at exactly the moment you need it."},
 {h:"Corporate prayer is different from private prayer", d:"'Where two or three gather in my name, I am there' (Matthew 18:20). Something happens in praying together that cannot happen alone. Don't neglect it for the convenience of solo faith."},
 {h:"Journaling as spiritual practice", d:"Many of the Psalms appear to be David's journal entries — raw, honest, unpolished. A spiritual journal is not a performance. Write what's actually happening between you and God."},
 {h:"Praying the Psalms", d:"The Psalms are a complete emotional range — lament, praise, anger, confusion, joy. When you don't know how to pray, find a Psalm that matches your mood and read it aloud to God."},
 {h:"Sabbath rest as spiritual discipline", d:"Rest is commanded, not optional (Exodus 20:8–11). One full day without work or productivity is an act of trust that God runs the universe without your help."},
 {h:"Service as worship", d:"Romans 12:1 calls presenting your body in service a 'true and proper worship.' Every act of service done in God's name is a form of prayer with your hands."},
 {h:"Waiting is a spiritual posture", d:"'Wait for the Lord; be strong and take heart and wait for the Lord' (Psalm 27:14). Waiting is not passive — it is an active exercise of trust when nothing appears to be happening."},
 {h:"Repentance: changing the direction you face", d:"The Greek word metanoia means a complete change of mind and direction. Repentance is not just feeling bad — it's turning and walking the other way. Repeated daily if necessary."},
 {h:"Lament: the prayer of honest pain", d:"One third of the Psalms are laments. Telling God exactly how bad it is — without premature resolution — is not a lack of faith. It's deep faith that he can handle the truth."},
 {h:"Practicing the presence of God", d:"Brother Lawrence, a 17th-century monk, practised speaking to God in all tasks — washing dishes, cooking, working. Try addressing God in your ordinary work today, not just in 'prayer time.'"},
 {h:"Praying Scripture back to God", d:"Find a promise in Scripture and pray it back: 'Lord, you said you would not leave me or forsake me (Deuteronomy 31:6) — I am standing on that today.' It anchors prayer in what God has already said."},
],

// ── WORLD — Bible knowledge, church history, theology ───────────────────────
world: [
 {h:"The Bible has 66 books", d:"39 in the Old Testament, 27 in the New Testament. Written over 1,500 years by about 40 different authors — in Hebrew, Aramaic, and Greek — yet with a unified story running through all of it."},
 {h:"The shortest verse in the Bible", d:"'Jesus wept.' (John 11:35) — two words in English, three in Greek. Jesus is at the tomb of Lazarus, whom he is about to raise. He weeps anyway. God is moved by your grief even when he already knows the outcome."},
 {h:"The Dead Sea Scrolls", d:"Discovered in 1947, the Dead Sea Scrolls contain the oldest known manuscripts of most Old Testament books — 1,000 years older than anything previously known. They confirmed that the text had been copied with extraordinary accuracy."},
 {h:"The Council of Nicaea (325 AD)", d:"The first great council of the early church, called by Emperor Constantine, addressed the question of who Jesus is. The Nicene Creed emerged from it — and it's still recited in churches worldwide 1,700 years later."},
 {h:"What the word 'Gospel' actually means", d:"Gospel is the Greek word 'euangelion' — literally 'good news.' In Roman culture, a euangelion announced a military victory or an emperor's birth. The first Christians used the same word to describe Jesus."},
 {h:"The Psalms: 150 songs that cover everything", d:"The Psalms are the longest book in the Bible and contain the full range of human emotion — joy, fury, depression, awe, betrayal, and love. They were the prayer book and hymnbook of ancient Israel and remain so today."},
 {h:"Paul wrote from prison", d:"Several of Paul's most beloved letters — Philippians, Ephesians, Colossians, Philemon — were written while he was in prison. 'I have learned to be content in all circumstances' was written in chains."},
 {h:"The word 'Amen' is Hebrew", d:"Amen means 'so be it' or 'truly' — it's a statement of agreement and affirmation. Jesus uniquely used it at the beginning of statements ('Amen I say to you...') to emphasise authority, not agreement."},
 {h:"Pentecost was an existing Jewish festival", d:"The day the Holy Spirit descended on the disciples (Acts 2) was already a major Jewish celebration — the harvest festival, fifty days after Passover. The disciples were in Jerusalem for the festival when it happened."},
 {h:"The Trinity is not a word in the Bible", d:"The word Trinity appears nowhere in Scripture, but the concept is threaded throughout: the Father speaks, the Spirit moves, the Son is present in Genesis 1 alone. John 1 explicitly identifies the Word as God and as distinct from God."},
 {h:"The Lord's Prayer has two versions", d:"Matthew 6:9–13 gives the fuller version we recite. Luke 11:2–4 gives a shorter version. Jesus apparently taught this prayer more than once, and the disciples asked to be taught it after seeing him pray."},
 {h:"John is the youngest of the twelve apostles", d:"John, author of the Gospel, three letters, and Revelation, is believed to have been a teenager when Jesus called him. He was the only apostle who did not die a martyr's death — he lived to extreme old age in Ephesus."},
 {h:"The Reformation started with 95 arguments", d:"On October 31, 1517, Martin Luther nailed his 95 Theses to the door of a church in Wittenberg — a standard academic practice for debate. He wasn't trying to split the church. Within weeks, printed copies had spread across Europe."},
 {h:"'Christianity' was a nickname", d:"The followers of Jesus were first called 'Christians' in Antioch (Acts 11:26) — it was likely a mocking nickname meaning 'little Christs' or 'Christ-people.' They kept it."},
 {h:"The Great Commission ends with a promise", d:"Matthew 28:19–20 — 'Go and make disciples of all nations... And surely I am with you always, to the very end of the age.' The command is enormous; the promise at the end is the reason it's possible."},
 {h:"Noah's ark was enormous", d:"Genesis 6 gives exact dimensions: 300 cubits long, 50 wide, 30 high — roughly 137m × 23m × 14m. Large enough to house thousands of animals according to modern calculations of the cubit."},
 {h:"The book of Job may be the oldest book in the Bible", d:"Many scholars believe Job was written before Moses, possibly in the time of the Patriarchs. It is also the most philosophically sophisticated book in Scripture — wrestling honestly with suffering and God's silence."},
 {h:"Mary Magdalene was the first witness of the resurrection", d:"All four Gospels agree: the first person to see the risen Jesus was a woman — Mary Magdalene (or women, including her). In a culture where women's testimony was legally inadmissible, the disciples were slow to believe her."},
 {h:"Baptism has three forms in Christian history", d:"Immersion (full submersion, practiced by Baptists and many others), affusion (pouring, common in Catholic and Anglican traditions), and aspersion (sprinkling). All three trace back to the early church."},
 {h:"The Beatitudes are backwards from worldly values", d:"Matthew 5:3–10 — blessed are the poor in spirit, the meek, those who mourn, the persecuted. Every beatitude describes someone the world passes over. Jesus calls them blessed."},
 {h:"The Lord's Supper has many names", d:"Eucharist (thanksgiving), Communion (sharing), the Lord's Supper (apostolic name), Mass (Catholic), the Breaking of Bread (Acts 2) — different traditions use different names but all point to the same meal Jesus instituted."},
 {h:"Hebrews 11 is called the 'Hall of Faith'", d:"Hebrews 11 lists Abel, Enoch, Noah, Abraham, Sarah, Moses, Rahab — people who 'died without receiving the promises.' Faith, the chapter insists, is moving toward what you cannot yet see."},
 {h:"The book of Revelation was written to seven real churches", d:"Revelation 2–3 contains specific letters to seven actual congregations in first-century Asia Minor (modern Turkey). They had real problems: apathy, false teaching, persecution, and wealth. The apocalyptic vision was encouragement, not just prediction."},
 {h:"'Paraclete' means more than 'comforter'", d:"The Greek word for the Holy Spirit in John 14 — Paraclete — means 'one called alongside.' A paraclete in Greek law was a legal advocate. The Spirit is not just comfort — it is active legal defence on your behalf."},
 {h:"The Sermon on the Mount is a complete ethical vision", d:"Matthew 5–7 is the longest continuous teaching of Jesus recorded. It covers anger, lust, divorce, oaths, revenge, enemies, giving, prayer, fasting, wealth, worry, judgment, and prayer — a complete ethical universe in three chapters."},
],

// ── CHALLENGE — Daily faith-in-action ───────────────────────────────────────
challenge: [
 {c:"Read one chapter of the Bible today — and sit with it for 5 minutes afterwards", y:"Reading without reflecting is like eating without tasting. The pause after the chapter is often where the real encounter happens."},
 {c:"Pray for three people by name today — not a list, a real conversation", y:"Specific names with specific needs. You're not broadcasting — you're bringing people you love to the God who loves them more."},
 {c:"Text someone to say you're praying for them — then actually pray", y:"Two things: the connection of telling them, and the discipline of following through."},
 {c:"Fast from social media for the day", y:"The noise of comparison, performance, and opinion is relentless. Give yourself one day of quiet."},
 {c:"Write down a sin pattern you're aware of and confess it to God honestly", y:"Confession is not cataloguing your failures — it's bringing them into the light where they lose their power."},
 {c:"Give something away today — money, time, or something tangible", y:"Generosity is a muscle. Every act of giving makes the next one a little easier."},
 {c:"Find someone lonely and spend time with them", y:"The elderly neighbour, the colleague who always eats alone, the family member no one calls. Jesus went to the margins; we can too."},
 {c:"Memorise one Bible verse today", y:"Write it on your hand, your mirror, or a card. Say it aloud ten times. Tonight, see if you can say it without looking."},
 {c:"Forgive someone in your heart who hasn't apologised", y:"Forgiveness is a choice before it's a feeling. Make the choice today — quietly, privately, between you and God."},
 {c:"Read Psalm 23 slowly, out loud, pausing at every comma", y:"You've heard it before. You haven't yet heard it the way reading it aloud in your own voice will make you hear it."},
 {c:"Attend a church service or faith gathering this week", y:"Faith grows in community. You can't get what the gathered Body offers anywhere else."},
 {c:"Tell someone what God has done for you recently", y:"Testimony — sharing what you've seen God do — is one of the most powerful forms of evangelism. No argument needed."},
 {c:"Do one anonymous act of service today", y:"No photo, no mention, no credit. The point is the act, not the recognition."},
 {c:"Sit in silence for 10 minutes with no phone, no music", y:"Stillness feels uncomfortable before it feels restorative. Ten minutes is long enough to experience both."},
 {c:"Write a letter of gratitude to God — just pour it out", y:"Not a prayer list. Just thanks. For specific things. Named. Write as if you were writing to someone who actually reads it. He does."},
 {c:"Pray the Lord's Prayer — one line at a time, slowly, pausing at each line", y:"'Your kingdom come' — stop. What does that mean for today? 'Give us today our daily bread' — stop. What are you actually asking for?"},
 {c:"Ask someone about their prayer needs and pray with them right then", y:"Don't say 'I'll pray for you.' Pray now. Together. Even two sentences. It changes something between you."},
 {c:"Read a chapter of Proverbs (the chapter matching today's date)", y:"Proverbs has 31 chapters — one for each day of the month. It's the most practical wisdom book in Scripture."},
 {c:"Tithe something today, even if it's small", y:"If you've been putting off giving, start now. Give one amount, to one place, on purpose. That's how the habit begins."},
 {c:"Go on a prayer walk — talk to God about what you see", y:"Pray for the houses you pass. The people you see. The community around you. Walking prays differently than sitting."},
 {c:"Read one story from the Gospels — and ask 'what does this show me about who Jesus is?'", y:"Not what it says to apply. Just: who is this person? Let the portrait settle before you extract a lesson."},
 {c:"Fast from complaining today", y:"Every time you notice a complaint forming, redirect it into a prayer. 'This is hard, Lord' is not complaining — it's honesty. 'This is ridiculous' discharged at someone else is."},
 {c:"Write a blessing for one person in your life and send it to them", y:"Not generic. Specific: what you see in them, what you're praying for them, what you're grateful for in them."},
 {c:"Ask God one honest question and sit with the silence", y:"You don't need an answer today. You just need to ask. The relationship deepens when the questions are real."},
 {c:"Read the Beatitudes (Matthew 5:3–10) and ask which one is your invitation today", y:"Eight descriptions. One of them probably lands differently than the others right now. That's the one."},
 {c:"Spend your commute or drive in prayer instead of music", y:"Not listening to worship — talking. Tell God about your day before it starts. It changes how you enter it."},
 {c:"Choose one Fruit of the Spirit to focus on this week — start today", y:"Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control. Pick one. Look for one chance to practise it."},
 {c:"Call an elderly person in your church or family — just to listen", y:"Older believers carry decades of faith stories. They often have no one to tell them to. Ask about their walk with God."},
 {c:"Confess something to a trusted friend or mentor today", y:"James 5:16: 'Confess your sins to each other and pray for each other so that you may be healed.' Accountability is a sacrament the church often skips."},
 {c:"Read Acts 2 — and ask what is the same and different in your church today", y:"The original church: devoted to teaching, fellowship, breaking bread, and prayer. No judgement — just honest reflection on the distance."},
 {c:"Write three things you're trusting God for right now", y:"Faith is not just retrospective (what God has done) but prospective (what you're waiting for). Name them."},
 {c:"Eat a meal slowly, giving thanks for each element — who grew it, made it, delivered it", y:"Grace before meals was designed to do this. Take five minutes to mean it today."},
 {c:"Do something today that you can only explain by faith", y:"Give more than is comfortable. Help someone inconveniently. Take a risk in obedience. Faith shows in choices the world can't fully explain."},
]
};

// ── PRAISE SONGS — Song of the Day pool ─────────────────────────────────────
const PRAISE_SONGS = [
  {t:"Way Maker",a:"Sinach"},
  {t:"Goodness of God",a:"Bethel Music"},
  {t:"What a Beautiful Name",a:"Hillsong Worship"},
  {t:"Oceans (Where Feet May Fail)",a:"Hillsong United"},
  {t:"Reckless Love",a:"Cory Asbury"},
  {t:"Build My Life",a:"Housefires"},
  {t:"Living Hope",a:"Phil Wickham"},
  {t:"Holy Spirit",a:"Francesca Battistelli"},
  {t:"How Great Is Our God",a:"Chris Tomlin"},
  {t:"10,000 Reasons (Bless the Lord)",a:"Matt Redman"},
  {t:"Great Are You Lord",a:"All Sons & Daughters"},
  {t:"King of My Heart",a:"Bethel Music"},
  {t:"Do It Again",a:"Elevation Worship"},
  {t:"Graves Into Gardens",a:"Elevation Worship"},
  {t:"The Blessing",a:"Kari Jobe & Cody Carnes"},
  {t:"Raise a Hallelujah",a:"Bethel Music"},
  {t:"Surrounded (Fight My Battles)",a:"UPPERROOM"},
  {t:"Ever Be",a:"Kalley Heiligenthal"},
  {t:"Even So Come",a:"Kristian Stanfill"},
  {t:"In Christ Alone",a:"Keith & Kristyn Getty"},
  {t:"Amazing Grace (My Chains Are Gone)",a:"Chris Tomlin"},
  {t:"O Come to the Altar",a:"Elevation Worship"},
  {t:"Glorious Day",a:"Passion"},
  {t:"God of Revival",a:"Brian & Jenn Johnson"},
  {t:"Battle Belongs",a:"Phil Wickham"},
  {t:"Firm Foundation (He Won't)",a:"Cody Carnes"},
  {t:"Gratitude",a:"Brandon Lake"},
  {t:"Holy Forever",a:"Chris Tomlin"},
  {t:"Champion",a:"Bethel Music"},
  {t:"See A Victory",a:"Elevation Worship"},
  {t:"Canvas and Clay",a:"Pat Barrett"},
  {t:"Your Presence Is Heaven",a:"Israel Houghton"},
  {t:"Nobody Like You Lord",a:"Vertical Worship"},
  {t:"Isaiah 6",a:"Phil Wickham"},
  {t:"This Is Amazing Grace",a:"Phil Wickham"},
];

// ── PILLAR SKILLS — shown when user's character matches ─────────────────────
const PILLAR_SKILLS = {

// ── BEAVER — Stewardship & generosity ──
beaver:[
 {e:"🙏",t:"Start tithing — even 2%",why:"The tithe is not a tax; it's a training. Starting small and increasing is better than waiting until you can give 10% perfectly.",steps:["Calculate 10% of your income — write the actual number down","If that's not possible now, choose a percentage you can start with today","Set up an automatic transfer to your church or a faith cause on payday"]},
 {e:"💛",t:"Give something away this week",why:"Generosity breaks the grip of money. Every deliberate act of giving reorders what sits on the throne of your finances.",steps:["Identify one thing you can give: money, a possession, your time","Give it this week — not when it's convenient, but as a discipline","Don't announce it. Notice what it does to you internally."]},
 {e:"📖",t:"Read what Jesus says about money",why:"Jesus talked about money more than almost any other subject. Most Christians don't know what he actually said.",steps:["Read Luke 12:13–34 — the parable of the rich fool and the teaching that follows","Write down one line that challenges you most","Bring that challenge to God in prayer before doing anything else"]},
 {e:"💰",t:"Build an emergency fund — as an act of wisdom, not fear",why:"Proverbs 21:20: 'The wise store up choice food and olive oil, but fools gulp theirs down.' Saving is stewardship, not selfishness.",steps:["Open a separate savings account if you don't have one","Set a first goal: one month of essential expenses","Automate a small transfer every payday — even $20 starts the habit"]},
 {e:"📊",t:"Create a budget that includes giving first",why:"A budget built on kingdom priorities looks different from a standard budget. Giving comes before spending — not from what's left over.",steps:["List income and all fixed expenses","Put giving at the top before discretionary spending","Adjust other categories to make it work — not the giving"]},
 {e:"🫶",t:"Sponsor a child or fund a specific cause",why:"Giving with a face changes giving. When you know who the money reaches, it shifts from transaction to relationship.",steps:["Research one organisation aligned with your values (Compassion, World Vision, local food bank)","Choose an amount you can sustain monthly","Set it up today — recurring is more valuable than one-off"]},
 {e:"🔄",t:"Practise contentment for one week",why:"1 Timothy 6:6: 'Godliness with contentment is great gain.' Contentment is not passivity — it's a discipline of satisfied trust.",steps:["For one week, buy nothing non-essential","Notice every moment you reach for something to fill a gap","At the end of the week, write what you noticed about yourself"]},
],

// ── WOLF — Body as temple ──
wolf:[
 {e:"🙏",t:"Make your morning routine an act of worship",why:"The body is God's temple (1 Corinthians 6:19). What you do first in the morning sets the spiritual temperature of the day.",steps:["Before checking your phone tomorrow morning, spend 5 minutes in prayer or Scripture","Include your physical routine (shower, breakfast) in your morning offering to God","Offer your body and day explicitly: 'Lord, this body is yours today'"]},
 {e:"🚶",t:"Go on a prayer walk today",why:"Movement and prayer were natural partners in Scripture. Jesus walked and talked with his disciples. Walking changes the quality of thought and prayer.",steps:["Plan a 20-minute route near your home","Leave the earphones behind — just walk and talk to God","Pray for what you see: people, buildings, the community around you"]},
 {e:"😴",t:"Protect sleep as a spiritual discipline",why:"God 'grants sleep to those he loves' (Psalm 127:2). Sleep is not laziness — it's trust that God runs the world without your constant effort.",steps:["Set a consistent bedtime for this week — even on weekends","Dim screens an hour before bed and spend that time in quiet","Notice whether better sleep changes your prayer and patience"]},
 {e:"🥗",t:"Fast from one food for one week and track what changes",why:"Fasting is not only about full-day fasts. Removing something you rely on for comfort reveals what you've been using in God's place.",steps:["Choose one comfort food or drink you reach for habitually","Give it up for seven days","Every time you reach for it, pray instead. Notice what you were actually hungry for."]},
 {e:"🌿",t:"Spend 20 minutes in nature today",why:"'The heavens declare the glory of God' (Psalm 19:1). Creation is a form of revelation — being in it is a spiritual act.",steps:["Step outside with no earphones and no agenda","Look for one thing in creation that shows you something about God","Thank God for that one thing specifically when you come back inside"]},
 {e:"💪",t:"Exercise for gratitude, not guilt",why:"Shame-based exercise doesn't last. But 'I get to use this body God gave me' is a sustainable foundation.",steps:["Before your next workout, say out loud: 'This is an act of gratitude'","Do something physical today — walk, stretch, lift, swim","After finishing, take one minute to thank God for what your body can do"]},
 {e:"🌙",t:"End the day with the Examen",why:"The Daily Examen (a Jesuit practice) is a simple review of the day in God's presence — where was he? Where did you miss him? It integrates faith and body into one honest daily review.",steps:["Before sleep, lie quietly and review the day in God's presence","Where did you feel most alive? Where did you feel most drained?","Name one gratitude and one thing you'd do differently — then rest"]},
],

// ── CAT — Prayer & contemplation ──
cat:[
 {e:"🕯️",t:"Try lectio divina this week",why:"Lectio divina (divine reading) is an ancient practice of slow, prayerful Scripture reading. It treats the text not as information to extract but as a word to encounter.",steps:["Choose a short passage — 4–8 verses","Read it slowly four times: for the whole, for a word, for a message, in response","Sit in silence for 5 minutes after the fourth reading. Let God speak."]},
 {e:"🌅",t:"Build a morning prayer practice",why:"The Psalmist prays 'in the morning' repeatedly (Psalm 5:3, 88:13, 143:8). Morning prayer sets the orientation of the whole day.",steps:["Choose a time — 5 minutes earlier than you currently wake","Pray using a simple structure: gratitude → confession → request → silence","Do it for 21 days and see how the practice becomes a need"]},
 {e:"📓",t:"Start a prayer journal",why:"Writing to God changes the quality of prayer. It slows you down, forces honesty, and creates a record of what you asked for and what happened.",steps:["Get a simple notebook — nothing fancy","Date each entry and write as if writing a letter to someone who is actually there","Review old entries quarterly. You'll be surprised what you see."]},
 {e:"🙏",t:"Practise the Lord's Prayer as a framework",why:"Jesus gave this prayer not as words to recite but as a structure to use. Each petition can hold an entire area of prayer.",steps:["Pray through Matthew 6:9–13 one line at a time, pausing at each line","Let each line open a category: praise, surrender, provision, forgiveness, protection","Use it as a scaffold, not a script — it should expand, not limit"]},
 {e:"🤫",t:"Practice 10 minutes of silence before God daily",why:"Psalm 46:10: 'Be still, and know that I am God.' Contemplative traditions teach that most of us need to practise silence before we can truly hear.",steps:["Set a timer for 10 minutes","Sit comfortably and bring your attention back to God each time it wanders — without judgement","Don't try to feel anything. Just stay."]},
 {e:"🧘",t:"Learn the breath prayer",why:"The Eastern Orthodox 'Jesus Prayer' — Lord Jesus Christ, Son of God, have mercy on me — is prayed on the breath. It can be carried through the whole day.",steps:["Inhale: 'Lord Jesus Christ, Son of God'","Exhale: 'have mercy on me, a sinner'","Practise for 5 minutes in a quiet place. Then carry it into your day."]},
 {e:"🌙",t:"End the day with evening prayer",why:"Compline — the ancient evening prayer — is a practice of ending the day with surrender. 'Into your hands I commit my spirit' (Psalm 31:5) was Jesus's last sentence before he died.",steps:["Before sleep, read Psalm 4 or 91 aloud","Name what happened today — good and hard — and give it back to God","Lie down and say: 'Into your hands I commit this night.' Then sleep."]},
],

// ── LION — Courage & boldness in faith ──
lion:[
 {e:"🦁",t:"Share your faith with one person this week",why:"'Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have' (1 Peter 3:15). You don't need a script — just your story.",steps:["Think of one person who doesn't know you're a believer","Find a natural moment this week — not a confrontation, just a conversation","Tell them what your faith means to you, simply and honestly. Then listen."]},
 {e:"⚡",t:"Pray for something specific and big",why:"James 4:2: 'You do not have because you do not ask God.' Many Christians' prayers are too safe. Ask for something large enough that only God could do it.",steps:["Name one thing that feels too big to ask for","Write it down as a specific, dated prayer request","Ask God for it directly and boldly — then watch the date"]},
 {e:"🛡️",t:"Identify one spiritual battle you're facing and fight it",why:"Ephesians 6 describes spiritual warfare with real armour for a real battle. Passivity is not an option — but neither is panic. Know what you're fighting.",steps:["Name one area where you sense spiritual opposition (temptation, discouragement, doubt)","Find a specific promise in Scripture that speaks to it","Pray that promise out loud, daily, for two weeks. This is fighting."]},
 {e:"🔥",t:"Say yes to one scary act of obedience",why:"Courage in faith is not the absence of fear — it's obedience in the presence of fear. God regularly asked people to do things that terrified them.",steps:["Identify one thing you sense God has been nudging you toward","Name what specifically makes you afraid to do it","Take the first step this week — just the first one. The next will follow."]},
 {e:"🗣️",t:"Speak up for justice in one specific situation",why:"Proverbs 31:8: 'Speak up for those who cannot speak for themselves.' Christian courage is not only personal — it's public.",steps:["Identify one person or group who is being treated unjustly in your sphere","Name one action available to you: a word, a choice, a letter, a vote","Take that action. Document it. Pray over it."]},
 {e:"✝️",t:"Stand firm in a moment of peer pressure",why:"Daniel refused the king's food. Shadrach refused the bow. Ruth refused to leave Naomi. The Bible is full of people who said no to pressure and yes to faithfulness.",steps:["Name one area where you've been quietly going along with something that contradicts your faith","Decide in advance what you'll do the next time it comes up","Practise the phrase: 'That's not something I do, but I respect your choice.'"]},
 {e:"🙌",t:"Volunteer for something that intimidates you at church",why:"God uses people who say yes before they feel ready. Gideon felt the least qualified. Moses had a stammer. God chose them anyway.",steps:["Find one opening in your church that you've thought about but avoided","Sign up this week — tell someone so you're accountable","Show up prepared and trust that God works through willingness, not perfection"]},
],

// ── EAGLE — Kingdom leadership ──
eagle:[
 {e:"👑",t:"Lead a devotion or discussion for your group",why:"Teaching others is the fastest way to deepen your own understanding. You don't need to be a pastor — you need to have prepared and be willing.",steps:["Choose a short passage — one paragraph or story from the Gospels","Prepare three questions to ask, not three points to make","Lead the conversation. Listen as much as you speak."]},
 {e:"🌱",t:"Mentor one person in faith",why:"Paul mentored Timothy. Barnabas mentored Paul. Jesus mentored twelve. No faith grows without someone investing in it.",steps:["Identify one person who is younger in faith than you","Ask if they'd be willing to meet monthly to talk about faith","Come prepared. Share honestly. Tell them about your struggles, not just your victories."]},
 {e:"🗣️",t:"Practise servant leadership this week",why:"Mark 10:45: Jesus 'did not come to be served, but to serve.' Kingdom leadership is defined by this — authority in the form of service.",steps:["Choose one moment this week where you would normally be served and serve instead","Do it without announcing it","Reflect: what does it feel like to lead from beneath rather than above?"]},
 {e:"📚",t:"Read one book on Christian leadership or mission",why:"Leaders read. The best Christian leaders have always been intellectually serious. Read widely, apply carefully.",steps:["Choose one book: 'Strengthening the Soul of Your Leadership' (Barton), 'The Deeply Formed Life' (Piper), or 'Leading on Empty' (Hybels)","Read one chapter this week — then talk to someone about it","Apply one idea before you finish the book"]},
 {e:"🌍",t:"Pray for a missionary or global church this week",why:"The church is global — and most Western Christians have almost no awareness of the Body outside their own culture.",steps:["Find one missionary or church in a country outside your own","Read their update or story — take five minutes to understand their context","Pray specifically for them: by name, for their specific situation"]},
 {e:"🏛️",t:"Identify your spiritual gifts and use one intentionally",why:"Romans 12 and 1 Corinthians 12 describe a body where every part has a function. Unused gifts are a loss to the Body.",steps:["Take a simple spiritual gifts assessment (many are free online)","Identify your top two or three — they're often things you do naturally that bless others","Find one place this month to deploy one gift on purpose"]},
 {e:"🤝",t:"Reconcile a broken relationship",why:"Matthew 5:23–24: leave your gift at the altar and go be reconciled first. Broken relationships in the Body are a direct obstacle to worship.",steps:["Name one strained or broken relationship in your life","Pray for that person by name every day for two weeks","Then go — not to be right, but to restore"]},
]

};
