name = "throbbing-bush-2964"
main = "index.js"
compatibility_date = "2024-09-23"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "LM_KV"
id = "d14577d7a56e4c7fbe67cd414df91901"

[triggers]
crons = ["* * * * *"]
